### ISSUE TITLE
Reduce Maker Party banner pattern size

### ISSUE THREAD

**Issue by sabrinang** [mozilla/teach.webmaker.org#1024]
![screen shot 2015-06-11 at 11 19 24 am](https://cloud.githubusercontent.com/assets/2492510/8114764/c4d90fbc-102b-11e5-9572-5e40ad26fdd5.png)

Reduce maker party pattern by 50% - pattern exported here: https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eTzVBdWRLcjdXbk0/view?usp=sharing
(use current pattern file as retina)

**Comment by mmmavis** [comment]
Hey @sabrinang ,

Just wanted to confirm - so the pattern size is 416x296 and the background image should be used as tiles? (e.g., [`background-repeat: repeat`](https://developer.mozilla.org/en-US/docs/Web/CSS/background-repeat))

**Comment by mmmavis** [comment]
Um... since this is an enhancement ticket and requires relatively small code changes... @sabrinang do you wanna take this on?  I think this will be a great starting point for your "learning to use git and CSS" goal :+1:  

I'll be in the office tomorrow so I can walk through the CSS changes as well as the code submitting  process with you. :bowtie: Let me know!

**Comment by sabrinang** [comment]
+100000000 good idea yes! :dancers:

**Comment by toolness** [comment]
yay mentoring ftw!
