### ISSUE TITLE
Download links for Maker Party assets should point to stuff.webmaker.org, not stuff.webmaker.org.s3.amazonaws.com

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/teach.webmaker.org#1038]
The links to download Maker Party assets (logos, brand palette, buttons, etc.) here https://teach.mozilla.org/events/resources/#logo-assets all lead to "untrusted connection" error pages. 

See the screenshot below that was sent to us by a Regional Coordinator.  I just checked and am receiving the same errors.
![screen shot 2015-06-17 at 4 42 27 pm](https://cloud.githubusercontent.com/assets/4885898/8207331/c73e1386-14ce-11e5-99fd-12bdc34f761b.png)

**Comment by toolness** [comment]
The technical details say:

```
stuff.webmaker.org.s3.amazonaws.com uses an invalid security certificate.

The certificate is only valid for the following names:
  *.s3.amazonaws.com, s3.amazonaws.com

(Error code: ssl_error_bad_cert_domain)
```

Any suggestions on how to fix this mister @jbuck ?  One option is to change all our links so that they use the path-based S3 URL syntax instead of the subdomain-based one, e.g.:

https://s3.amazonaws.com/stuff.webmaker.org/teach.mozilla.org/MakerPartyBrandPalette.eps

I am surprised that Amazon's SSL cert *used* to work but doesn't anymore, though.

**Comment by jbuck** [comment]
@toolness Don't use the bucket name, use https://stuff.webmaker.org/teach.mozilla.org/MakerPartyBrandPalette.eps

**Comment by toolness** [comment]
Ahhh got it, thanks jbuck!

@mmmavis can you fix this one real quick?

**Comment by toolness** [comment]
Hmm actually don't worry about it, I'm blocked on the Discourse migration stuff at the moment, so I can deal with this now!
