### ISSUE TITLE
Update headlines on Maker Party activity page

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/teach.webmaker.org#1102]
Instead of:
* Section 1: Reading the Web
* Section 2: Writing the Web
* Section 3: Participating on the Web

Can we change to:
* Reading the Web
* Writing the Web
* Participating on the Web

Apologies for not catching this sooner.

**Comment by hannahkane** [comment]
assigning to @toolness for east coast speediness

**Comment by toolness** [comment]
Because of the way we're reusing code across all our activity pages, the only easy way to do this will be to also remove the "Section X:" from the headings in the [Web Literacy Basics](https://teach.mozilla.org/activities/web-lit-basics/) and [Protect Your Data](https://teach.mozilla.org/activities/protect-your-data/) pages as well. This seems like a good idea anyways to me, since it makes the section headings consistent across our pages, but I wanted to check to make sure it's ok with you before pushing the changes to production.

**Comment by hannahkane** [comment]
OK with me. @ldecoursy?

**Comment by ldecoursy** [comment]
I'm talking about just removing those phrases from this page https://teach.mozilla.org/activities/maker-party-2015/

**Comment by toolness** [comment]
yeah, i know, it's just that that page is reusing code from the other two pages, and that reused code is hard-coded with the word "Section" at the beginning... i *can* make it so those other pages still say "Section X:" in the headers, but it will involve a bit of additional work, and also feels odd to me because it makes the pages appear inconsistently formatted (i.e. why are we saying "Section X:" in the web lit basics page but not in the maker party activities page?).

**Comment by ldecoursy** [comment]
Got it - ok let's go for it. Thank you!
