### ISSUE TITLE
Update email response after user applies to add their club

### ISSUE THREAD

**Issue by thornet** [mozilla/teach.webmaker.org#1104]
A ticket as an result of #1085

Email copy here:
https://github.com/mozilla/teach-api/blob/master/clubs/email.py

Suggested edits: 

%(username)s,
Thanks for your interest in Mozilla Clubs. 

As mentioned on the website, we're currently at capacity for clubs that can be supported directly at this stage. We will be in touch when we're accepting new clubs. 

NEVERTHELESS! You can begin to teach the web right away with these fun learning activities [https://teach.mozilla.org/activities/]. 

There are also lots of amazing resources [https://teach.mozilla.org/clubs/] to help you organize a group of learners, to embed web literacy into your practice and to be a more effective open leader. 

If you'd like additional support or to meet fellow educators and activists in the network, say hello in our discussion forum [http://discourse.webmaker.org/category/clubs], or tweet using hashtag #teachtheweb.

Michelle Thorne,
on behalf of the Mozilla Learning Network

**Comment by thornet** [comment]
cc 
* @ldecoursy @amirad to proofread
* @hannahkane @toolness to help implement

**Comment by ldecoursy** [comment]
Should we add a note re: Regional Coordinater recruitment? We're looking for more volunteer Regional Coordinators to help us support new Mozilla Clubs. Please visit (link to RC role) for more information.?

**Comment by toolness** [comment]
Rad! Just so you know, right now we can only send plain-text emails, which means we can't hyperlink text like we can in HTML. That means that all he links in the email will appear exactly as you have written them out in the [issue description](https://github.com/mozilla/teach.webmaker.org/issues/1104#issue-95225576) above.

**Comment by thornet** [comment]
Note to work into the text: 

* Successful clubs need relationships with RCs. Explain the rationale.

**Comment by hannahkane** [comment]
Adding blocked label until we have final copy

**Comment by chrislarry33** [comment]
need copy asap. A few comments

1) I understand the rationale, not suggesting change. But I do think this can't lose batches of interested people. So the messaging and offer has to  be tight, engaging and motivational. Needs to be right. Can we enlist @HPaulJohnson here for help? Can we test some?

2) Have we considered what a club light, or a "I am starting my club and am hoping to apply for Moz Club status later" version might be offered? Are their steps in evolving application process we want to activate here (post on blog/discourse/join RC interest meeting/contact RC/do activity(s) fill out review form etc) we can offer?

3) Can we find a different way to say "at capacity" that doesn't change the meaning?

4) Less superlatives, more details

**Comment by thornet** [comment]
Yes, I very much in need of help drafting. Took another stab with feedback from above: 

%(username)s,
Thanks for your interest in teaching the web!

Get started right away with these fun learning activities: https://teach.mozilla.org/activities/.

Mozilla Clubs are most successful when paired with a volunteer Regional Coordinator. Our first cohort of Regional Coordinators is already in full swing right now, so there is not one available to assist you at this time. 

Nevertheless, you can still use these resources to organize learners and bring the web to life, and we'll be in touch once more Regional Coordinators are ready to support you directly: https://teach.mozilla.org/clubs

Need more? Find inspiration and meet fellow educators and activists. Say hello in our discussion forum (http://discourse.webmaker.org/category/clubs), or tweet using hashtag #teachtheweb.

Michelle Thorne,
on behalf of the Mozilla Learning Network

**Comment by thornet** [comment]
+1 to @chrislarry33 idea of what a light application can look like. Might revise last paragraph to be about posting "your vision for your club" etc. in Discourse.

**Comment by toolness** [comment]
Yeah, +100000 to using Discourse more!

**Comment by HPaulJohnson** [comment]
@thornet @chrislarry33 would love to help. have a few things this morning to wrap up and then will jump in.

**Comment by HPaulJohnson** [comment]
I think the idea of telling people they've been added to a "wait list" is a strong approach here; it's softer than "no" and in many cases creates a positive effect through scarcity and increased desire to be part of something in such high demand. I think @thornet's most recent copy does a pretty good job of this but I would probably say right up front, "thanks for your interest," "you've been added to our waiting list" and (ideally) set some expectation about "wait time" they can expect to be in queue (weeks, months, etc). 

I'd also advocate that there is still some type of lightweight intake form or application. The real risk is that you turn away your next RC or a super impactful Club Captain. Getting enough information so that we can still identify potential superstars through this flow is critical as we aim to build a quality network. 

I also wonder if the capacity has been reached across all regions or are there particular places that are fuller than others? Maybe our logic for who is in and who is wait listed can be more dynamic, instead of applying a global approach to everyone at the top of this funnel. 

Finally, what's the best way to invite them to engage outside of a full-blown club? The message still feels a bit like "thanks but you are on your own." Discourse works if it comes across as engaging in a relationship rather just posting something on a message board. Could also suggest they run something like a Maker Party as a pilot for clubs. This would engage them more deeply in our program and would give us a mechanism for identifying people who would be really strong captains or coordinators.

**Comment by hannahkane** [comment]
Any movement or plans for this one?

**Comment by anmechung** [comment]
+1 to Paul's comments about crafting the right message.  I also wonder if we should explore multiple ways to scale that may not be as time consuming , i.e. an online or in-person train-the-trainers where an RC can ramp up large numbers (100?) of CCs.  Chad and I are exploring this for afterschool educators, and have thumbs up to do something like this in the spring.

**Comment by thornet** [comment]
Revised text: 

%(username)s,
Thanks for your interest in teaching the web!

Get started right away by guiding a group of learners through these featured activities: https://teach.mozilla.org/activities/

We believe in the power of peer learning. That's why we match each Mozilla Club Captain with a volunteer Regional Coordinator who can support you in getting started and making the most of this program. 

Please note: Our first cohort of Regional Coordinators is in full swing right now, so you've been added to our waiting list. We'll match you with a Regional Coordinator as soon as we can. Your club will not show up on the map until you've been matched up. 

To begin on your own, check out these resources to organize and teach your learners: http://mozilla.github.io/learning-networks/clubs/#resources 

Please also say hello in our discussion forum (http://discourse.webmaker.org/category/clubs) or tweet using hashtag #teachtheweb if you need any help. 

Let's teach the web! 

Michelle Thorne
on behalf of the Mozilla Learning Network

**Comment by hannahkane** [comment]
Thanks, @thornet. I'm going to close this ticket and open a separate one for implementation, since this ticket is so fully commented. :)
