### ISSUE TITLE
Add "Name" field to Clubs form

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#1137]
Can be the first field, and can just be "Name."

**Comment by hannahkane** [comment]
@mmmavis - possible to do this this week?

**Comment by mmmavis** [comment]
Will also have to make edits to the database which I don't have access to.  I'll talk to @simonwex tomorrow and find out a solution.

**Comment by hannahkane** [comment]
no longer blocked

**Comment by mmmavis** [comment]
Ummm if we are adding a "name" field to the Clubs form, does that mean the same user can choose to enter a different name every time she/he proposes a Club?

I think it makes more sense to associate user's name with "User" instead of "Club".  And if this sounds like a better approach, how do we present it on the website so that users will only be asked to fill out their name once?

@hannahkane @sabrinang

**Comment by mmmavis** [comment]
FYI, id.webmaker doesn't collect name, it collects e-mail only.

**Comment by hannahkane** [comment]
@mmmavis - I agree. This would be a kind of strange solution. Let's nix this for now, and solve with the user profile that's coming via MLN Directory.

@Saallen - this means, unfortunately, that we won't be able to have first name in the meantime. :(

**Comment by Saallen** [comment]
:crying_cat_face: Understood. Thanks for trying though
