### ISSUE TITLE
PROD deploy is not working

### ISSUE THREAD

**Issue by mmmavis** [mozilla/teach.webmaker.org#1152]
v0.0.16 hasn't made its way to https://teach.mozilla.org :cry: You can check meta on https://teach.mozilla.org/healthcheck/

I'm creating a new ticket here so we can keep track of the issue. Earlier conversation can be found in https://github.com/mozilla/teach.webmaker.org/issues/1129

Assigning this to you, @simonwex :wink: 

/cc @hannahkane @jbuck

**Comment by jbuck** [comment]
Okay, here is what I think happened, and why it v0.0.16 didn't get released properly. For context, refer to the release docs:

- Mavis created a .16-rc PR based on develop
- Simon and Mavis added more commits to develop, but didn't update the .16-rc branch with these commits. Check out the network graph, and look at where develop branched from. The confusion continues when Mavis merged the .16-rc branch into master, and then tagged .16 on the develop branch instead of on the .16-rc branch that gets merged to master.

Recommended fixes:
1) Just merge the tag v0.0.16 into master and call it a day
2) Wait until v0.0.17 and ensure that it gets released properly

@simonwex I leave it up to you to decide!

**Comment by mmmavis** [comment]
@jbuck thanks for investigating this :+1: 

I always follow the [RELEASE.md](https://github.com/mozilla/teach.webmaker.org/blob/develop/RELEASE.md) step by step... not sure how I messed this up this time :no_mouth: :confused:

There are some PRs waiting to be merged and pushed so I personally prefer option 2.

**Comment by hannahkane** [comment]
Closeable, right? Hooray!

**Comment by mmmavis** [comment]
Reassigned this to myself.  

Some git drama happened when I tried to push a `v0.0.17` out today. Will need to work with @jbuck tomorrow to get this fixed. :confounded: :confounded: :confounded:

**Comment by mmmavis** [comment]
@jbuck 

interesting findings - 
I'm checking https://teach.mozilla.org/healthcheck/ (see screencap below) and it looks like [the 2 reversion commits](https://github.com/mozilla/teach.webmaker.org/commits/master) didn't get pushed live? I wonder why!

![screen shot 2015-08-12 at 2 52 55 pm](https://cloud.githubusercontent.com/assets/2896608/9237813/3c5ac178-4102-11e5-8cf4-efb784700553.png)

**Comment by mmmavis** [comment]
no longer an issue :dancer: thanks @jbuck !

**Comment by hannahkane** [comment]
woohoo!!!!!!!!!!!!!
