### ISSUE TITLE
Thimble promotion: implement email campaign 

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#1160]
The design work for both is in progress: https://github.com/MozillaFoundation/plan/issues/518

Wondering if @mmmavis will be available during the August 28 heartbeat to create the email template in BSD and add the banner to the Teach homepage.

/cc @simonwex

**Comment by sabrinang** [comment]
![mozilla-learning-network_email-template-bsd](https://cloud.githubusercontent.com/assets/2492510/9259877/39146728-41b9-11e5-9438-ad24d91487d6.jpg)

Assets here: https://drive.google.com/open?id=0B4Q8pzCpDS_eflc1NzdjMGpCRm1mVFpxTVA4b0hyR3NMRzlFdTNhc045U3FhbGlLbndIUTg

**Comment by mmmavis** [comment]
yea i think i should have time for this.  assigning this ticket to myself now :)

**Comment by mmmavis** [comment]
Done!

@HPaulJohnson you can now use and apply the template **"Thimble Email Template (August 2015)"** on BSD! :smile: Ping me if anything needs adjustment!

**Comment by mmmavis** [comment]
One design tweak suggested by @sabrinang : 
Use `teach-referral-bg-white-50%.png` for background image instead (50% opacity)

Let me update the BSD template now.

**Comment by mmmavis** [comment]
@HPaulJohnson FYI, max width for embedded images should be 548px for this one.

(it's 550px for the Webmaker template but this Thimble one has a 1px border around the container)

**Comment by HPaulJohnson** [comment]
@sabrinang do we need to redo the images to this spec (vs. resizing them in BSD once embedding like I have been doing)?

**Comment by sabrinang** [comment]
@HPaulJohnson Yes, I will export them to x2 the size (1096px width) so it renders well on retina displays which means you can resize them in BSD to 548px width which should solve the pixelation issue. I'll be exporting them now.

**Comment by sabrinang** [comment]
All assets exported here (includes original and 2x versions): https://drive.google.com/a/mozilla.com/folderview?id=0B4Q8pzCpDS_efkRlbG5yS2hFdmFZbnR3UHN0aUZrc1hqc2g2U0YxU1FTOWR4T3l4ZXVjVEE&usp=sharing

Also - I included a simplified screen option instead of screencap if you prefer:
Original screencap interface
![mozilla-thimble_email-image-screencap 2x](https://cloud.githubusercontent.com/assets/2492510/9534783/03542246-4cd0-11e5-9e78-b52d26b37131.png)
Interface vectorized (text seen as simplified rectangles)
![mozilla-thimble_email-image-vectorscreen 2x](https://cloud.githubusercontent.com/assets/2492510/9534786/04d4c440-4cd0-11e5-9cc2-52846a863363.png)
