### ISSUE TITLE
Change copy on Clubs modal

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#1174]
In order to accommodate programmatic shift (allowing for Club Captains to start their work without being matched to a RC), we'll need to change the copy on the Clubs modal, which currently looks like this:

![screen shot 2015-08-18 at 4 11 21 pm](https://cloud.githubusercontent.com/assets/8389648/9345258/eedf533e-45c3-11e5-8ac8-f874e395b9a7.png)

Modal title suggestion: Get matched with a Regional Coordinator [this aligns with the copy of the button they'll have just clicked]

Explanatory text suggestion: We have a waiting list for Regional Coordinators. Fill out the information below, and we'll match you as soon as we can.

**Comment by hannahkane** [comment]
@thornet @amirad—does the suggested copy above make sense to you?

**Comment by thornet** [comment]
<3. Thanks, @hannahkane! 

Would wait to see if @amirad has any other edits, but this looks good from my perspective.

**Comment by thornet** [comment]
Ah, this might be a good opportunity to add the field for "Full Name" (see #1137)

**Comment by hannahkane** [comment]
There's a recent conversation on #1137 about how adding a name field would be violating best practices. It doesn't really make sense to have the user's name associated with the Club data—this would allow, for example, a user to enter a different name for each of multiple Clubs. It will be better to attach the Name field to a user profile, which is in the roadmap, but not implemented yet.

@amirad - let us know if the copy suggested above works for you, as soon as you can, please.

**Comment by amirad** [comment]
Are we assuming only people with establish affiliations will be clicking to this form? I'm scared the first question scares away the average person. Perhaps instead "Who is your Mozilla Club have affiliations with (if any)" and making it a not mandatory field. 

Also a logistical point: some cities have the same names across provinces, states and countries (ex. portland, memphis, lebanon, mozcow etc). Might have to make that city and country if we want to get an actual feel for where these people are located. We've gotten tripped up over it in the past when collected location data. 

I don't come across many clubs that have a website, rather a page that lives somewhere else like meetup or coderdojo or eventbrite. Maybe changing "website" to "page" and adding "if applicable" instead of "optional" will sound less intimidating. 

When we get this info we will be able to match it to their email address right?

**Comment by hannahkane** [comment]
Sorry, I wasn't clear about the scope of this ticket. I didn't intend for it to be about changes to the form in general. This was just meant to provide copy changes that would correspond to the copy changes we're making on the /clubs page.

@amirad - I'll file separate tickets for the changes you suggested above.

Regarding matching the Clubs form to the email address, we're not making any changes to how this flow works. So, you'll continue to receive the "New Club has been submitted" emails that list the user's email address.

Going to assume we're good on the suggested copy changes, and see if @mmmavis is able to implement this.

**Comment by mmmavis** [comment]
merged to `develop` as parts of [PR#1198](https://github.com/mozilla/teach.webmaker.org/pull/1198)
