### ISSUE TITLE
[MIGRATED] Design graphics for Learning Pathways whitepaper

### ISSUE THREAD

**Issue by dajbelshaw** [mozilla/teach.webmaker.org#131]
### RACI
Driver: @hannahkane
Design Lead: @sabrinang 
Whitepaper project lead: @dajbelshaw 

Context: 
* https://github.com/mozilla/learning-pathways-whitepaper/issues/26
* http://goo.gl/yB5FFB 

@cassiemc: suggest @iamjessklein might be well-placed to do this? Looking to publish at end of Q1. :)

We'll use the same template as we did with the first [Webmaker whitepaper](https://mozilla.github.io/webmaker-whitepaper/) so these images are those mentioned in the [Google Doc](http://goo.gl/yB5FFB) (not finalised, and open to discussion).

**Comment by hannahkane** [comment]
I'll bring this to the planning meeting for the heartbeat that ends March 27, so we can allocate design resources then.

@dajbelshaw, can you add more detail to the ticket about what the design needs will be - is it formatting the paper? Will there be illustration work needed? Etc.

**Comment by dajbelshaw** [comment]
@hannahkane Done!

**Comment by hannahkane** [comment]
@dajbelshaw - I just heard this may have been accepted for publication elsewhere? Are we designing for that? (If so, is it print or online only? Is there a deadline associated with that?)

@cassiemc - it would be useful to me to have an estimate of design effort or time involved in order to make decisions about priority. Do you have enough information in this ticket to be able to estimate design resources needed?

**Comment by dajbelshaw** [comment]
Hi @hannahkane, no I haven't heard anything about this being accepted for publication elsewhere - unless @smithisgeneric knows more?

Perhaps you saw that Karen and I had something published in MIT's Civic Media Reader? That's separate thing! :)

**Comment by hannahkane** [comment]
@dajbelshaw, it's difficult for me to understand what the specific design needs are, even when reading through the doc. Can you create a list of the specific illustrations and/or images needed?

**Comment by dajbelshaw** [comment]
@hannahkane: Just waiting for a conversation with @iamjessklein :)

**Comment by hannahkane** [comment]
@sabrinang has been assigned to this ticket, which is a P2 in the current heartbeat. @sabrinang, if you finish your P1s, let @dajbelshaw and I know so that we can have a kick-off meeting.

@dajbelshaw - whatever you can do in advance of that meeting to help Sabrina and I understand the specific needs, the better! Thanks!

**Comment by iamjessklein** [comment]
@hannahkane I am removing the March 27 milestone here.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/52"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/52.
Please don't comment on it here.
