### ISSUE TITLE
Small changes to homepage

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#184]
1) The current site design has two user stories featured on the homepage - "Sadia's story" and "Masud's story". They both have "Learn more" links that go nowhere. 

Let's remove both stories for now, since we don't actually have current stories. :)

2) We have a copy change for the main paragraph. Currently reads, "Join our community of educators, parents, techies and makers who want to teach digital skills and web literacy through making."

Should read, "Join our community of educators and activists who want to teach digital skills and web literacy through making."

(The delta is to replace "educators, parents, techies and makers" with the more streamlined "educators and activists")

**Comment by ldecoursy** [comment]
I think since we have the user quotes, we could remove these additional user stories for now. Good to think about how we can collect and add for v2...

**Comment by chrislarry33** [comment]
+1 remove

**Comment by hannahkane** [comment]
Not sure who's in the best position to make changes like this. @toolness? @vazquez?

**Comment by toolness** [comment]
It's very easy for me to do, but I think this might actually make for a good first React-related issue for @vazquez, since I wrote some (arguably needlessly complex!) JSX to display those stories... It will involve getting rid of at least one React component I think.

Want to give it a shot @vazquez? No worries if not.

**Comment by vazquez** [comment]
Yeah I'll do it!
