### ISSUE TITLE
Model a local club's thread in Discourse and link to from landing page

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/teach.webmaker.org#208]
If you had just started a club, what would you say in Discourse announcing it? How would you prompt your new clubbers? What kind of laser light show would you include? And how would you encourage reflection?

**Comment by LauraHilliger** [comment]
@chadsansing - would you want to take a stab at this? I can wax theoretical, but since you've actually set up a club, maybe you remember your initial discussions? Or if you just dump your thoughts on what the FAQs and stuff were, I could try to set up a thread.

**Comment by chadsansing** [comment]
Yes. More soon.

**Comment by thornet** [comment]
<img src="http://media.giphy.com/media/dNZLGHSXh3DMI/giphy.gif">

**Comment by jgmac1106** [comment]
Chad

I can pretend to be a "fake" student if you need me to.

**Comment by chadsansing** [comment]
Okay, so here's a mock-up:

https://chadsansing.makes.org/thimble/MzM3NTE1NTI=/our-schools-web-club

I would use the same introductory copy on Discourse and link to a splash-page. Over time, the splash-page could become its own site with pages featuring different projects, events, or spin-offs of the original club.

I would add these observations:

*Know your audience and their perception of you. I play it goofy because few other people in traditional middle schools know what it is a Web Club might do. Keep the humor warm and inviting, though, if you use it. 
*Localize for your context.
*Repeat the details at least twice.
*Ask your administrator/supervisor/chief stakeholder to approve the club and announcement/webpage. In schools, you may need to make the webpage an official school webpage in whatever CMS your division has purchased. Be ready with some 'by creating memes, students will be able to..." blardy-blar.
*Make fliers that stand out from your local announcement norms.
*Link from your announcement and splash page to fliers for people to print and share. Include fliers of different color schemes (e.g. full color and grayscale), qualities, and sizes.
*Ask your space wranglers to approve any fliers you put up or invite others to put up in those spaces.
*Spam your channels. For schools this means hitting some combination of announcements, parent-communication folders (it's a thing), teacher mailboxes, fliers in the hallway, fliers in teacher workrooms, a blurb on the school website, articles in school, parent-teacher-organization, and/ or division newsletters, social media mentions (if applicable), and, whenever possible, visiting classes to make sure all kids know they are invited.
*Encourage new attendees and regular participants to bring friends.
*Be ready with the club Webmaker login.
*Brush up on badges. Be ready to help participants set up backpacks. Aspire to send out earned badges promptly after each session.

Let me know what else I can add here or on Discourse to be of service!

**Comment by jgmac1106** [comment]
I propose stripping @chadsansing <https://github.com/chadsansing>  of all
badges in his backpack Patrick Hand as a font looks suspiciously like Comic
Sans.

**Comment by LauraHilliger** [comment]
nice @chadsansing! @jgmac1106 doesn't know what he's talking about. I mean, he's right, the font resembles comic sans, but you should EARN a badge for not actually having used comic sans (or papyrus, which in my opinion is worse).

@chadsansing Is it cool if I take the content here and set up a [discourse](http://discourse.webmaker.org/category/clubs) thread with it? Would rather it be attributed to you, but also don't want to give you extra work here. We want to link the "preparation" note here: http://mozilla.github.io/webmaker-curriculum/WebLiteracyBasics-I/index.html

**Comment by chadsansing** [comment]
Okay - I will copy it into a discourse thread on 'Modeling/Preparing for
Your Local Club' - then you can do the link. Sound good?

Best,
C

**Comment by LauraHilliger** [comment]
yep! Thanks, you rule :straight_ruler:

**Comment by chadsansing** [comment]
Done - http://discourse.webmaker.org/t/preparing-to-launch-a-local-club/1273.

**Comment by chadsansing** [comment]
Thanks for the invitation to contribute!

Onward,
C

**Comment by LauraHilliger** [comment]
thanks Chad! Going to leave this open and assign it to myself so I can do some boldering ;)

**Comment by LauraHilliger** [comment]
@chadsansing I edited your post a bit to make it more like a thread inviting the learners to participate in discourse. Hope you don't mind! If you want to make more edits in that direction, please do (just don't change the thread name without letting me know, b/c the URL changes and I'll need to update the github link) 

It's now here: http://discourse.webmaker.org/t/our-new-local-web-club/1273 and linked from the basics index page.

Here's the pull: https://github.com/mozilla/webmaker-curriculum/pull/162

Again, hope you don't mind my edits! I was trying to sound like you ;)

**Comment by chadsansing** [comment]
I love (& often need) a good editor - thanks, Laura!

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/66"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/66.
Please don't comment on it here.
