### ISSUE TITLE
[MIGRATED] Write Club Leader on-boarding and guidelines with RCs

### ISSUE THREAD

**Issue by Saallen** [mozilla/teach.webmaker.org#23]
## RACI

* Phase: 
* Owner: 
* Decision Maker: 
* Design Lead: 
* Development Lead: 
* Quality Verifier: 

## Deliverables

 - [ ] TBD, but should end with RCs beginning to onboard new Club Leaders

**Comment by LauraHilliger** [comment]
we talked about this a little in our sustaining engagement call. Have scoped some things in the Teach Like Mozilla content (italics are topics scoped for TLM), and have noted:

### Your 1st Month as a Regional Coordinator
* (*Finding your Crew, Working Openly, Open Tools*) Focus in on Recruitment. Kickoff meetings. Protocols & patterns for coordinating clubs. How to connect with RCs and regions (video bridge / cross-region comms & connection)
* (*Sharing/Storytelling*) Talking points for how a club will add value to your club captain. 
* (*Sharing/Storytelling*) How to tell the story of the clubs so that the club captain can tell the story. 
* Includes regional case studies (i.e. Rio LAN houses, Chicago public schools)

### Your 1st Month as a Club Captain
* (*Remixing for Context*) How to set up your club or embed it in your existing program
* First 16hr of curriculum
* How to get help and connect with other clubs and your coordinator
* (*Sharing/Storytelling*) How to attract the public. 
* (*Sharing/Storytelling*) How to tell the story of the clubs so that the participants can tell the story.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/13"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/13.
Please don't comment on it here.
