### ISSUE TITLE
Figure out a way to run retina tests on the ImageTag component

### ISSUE THREAD

**Issue by gesa** [mozilla/teach.webmaker.org#259]
This needs to be uncommented and made to work!
https://github.com/mozilla/teach.webmaker.org/blob/develop/test/browser/imagetag.test.jsx#L23-L40

**Comment by toolness** [comment]
So the main thing that needs to be done here is to modify the global `window` object rather than a local one. One way to proceed is to use [Mocha's hooks](http://mochajs.org/#hooks) to save and restore the actual value of `window.devicePixelRatio` before and after test runs, and set `window.devicePixelRatio` within the tests.

If that doesn't work, e.g. because a host browser doesn't like you overwriting its stuff, then an alternative might be to pass a fake window object in as an additional prop, but use [default props](http://facebook.github.io/react/docs/reusable-components.html#default-prop-values) to have the global window be its default value, so that production code doesn't need to explicitly pass it in.

I should also note that I think that your existing test, just a little bit above the commented-out code, **might only pass on non-retina displays**. Once you fix this issue using one of the strategies I mentioned above (or a different one of your own invention) that should go away though!

**Comment by toolness** [comment]
Ah, I'm working from my retina MacBook Pro today and indeed the tests don't currently pass on it:

![screen shot 2015-03-16 at 9 56 01 am](https://cloud.githubusercontent.com/assets/124687/6667509/ee16613e-cbc2-11e4-85ab-9ff5a06919fb.png)
