### ISSUE TITLE
Make browser tests easier to debug

### ISSUE THREAD

**Issue by toolness** [mozilla/teach.webmaker.org#293]
@gesa and @alicoding both ran into the same problems when trying to debug browser tests:

* ~~Because `WEBPACK_DEVTOOL` defaults to `source-map` and no browser (even chrome) shows source-mapped lines in [mocha tracebacks](https://github.com/mozilla/teach.webmaker.org/pull/147#discussion_r25939671), we should probably default `WEBPACK_DEVTOOL` to `eval` for development, and `source-map` for production. Otherwise debugging browser tests is *extremely* frustrating.~~ Done in 71ee7e4cb7237bca0d0250adbe2c74550f3682aa.
* Aki and Ali were both using the command-line, which ran phantomjs, to run the tests, which has some limitations:
  * I'm not sure if phantomjs supports *any* kind of source mapping; if it doesn't, we should probably have a big message shown if a test fails that says **HEY GO TO http://localhost:8008/test/ TO DEBUG THIS**.
  * `console.log` statements show up in the browser but not phantomjs. We should either fix this or show the big message as per above.

@gesa, @alicoding - Are either of you interested in taking this on?

**Comment by alicoding** [comment]
@toolness I'm interested in working on this patch if @gesa is okay with that.

I tend to avoid using phantomjs lately because of debugging issue as well and had to always default to `eval` and in some case I have to use `chrome` to debug because Firefox sometimes doesn't seem to be happy with `eval` either.

I'm going to take sometime reading through **webpack** and probably anything that could help us get this debugging both on the browser and command-line to be easier. I'm sure people have had the same issue and must have solved it with something here.

**Comment by gesa** [comment]
My learning curve on this one is pretty high, so I'm okay with that @alicoding. Please lmk if you want help on it in any way though, more than happy to assist!

**Comment by toolness** [comment]
Just wanted to note that `WEBPACK_DEVTOOL` now defaults to `eval` for development, as of 71ee7e4cb7237bca0d0250adbe2c74550f3682aa.

**Comment by toolness** [comment]
Ok, in bf48f75e3088108fb0842b2824b049832dc4f434 I made the following very noticeable message appear if browser tests fail:

![2015-04-15_9-55-57](https://cloud.githubusercontent.com/assets/124687/7160254/e98b3d4c-e355-11e4-8459-0f13ff806991.jpg)
