### ISSUE TITLE
Meta: automated test sprint process

### ISSUE THREAD

**Issue by k88hudson** [mozilla/teach.webmaker.org#346]
Hey @hannahkane I just wanted to keep you in the loop about what @gvn and I are working on this sprint;

We've been tasked with improving automated testing, some of which focuses on teach and the new login work (some background here https://github.com/MozillaFoundation/plan/issues/351, although there is a lot there and it might not be very useful to read).

I've been filing new tickets on this repo with the tag `Automated tests` -- is that OK with you? Let me know if you'd prefer a different method of organization/grouping.

If you're OK with that, feel free to close this ticket.

**Comment by hannahkane** [comment]
Thanks, @k88hudson. Glad to know we are upping our testing game! 

I'm using the following meta data conventions:
 - using the "platform" label to distinguish anything site related from the programmatic work of the Learning Networks team. Due to a miscommunication on my part (that @simonwex is trying to fix), we are currently using this repo for the entire team's work, so I need the "platform" label to distinguish all of the site work.
 - using the "engineering" label to distinguish work to be done by engineers from the work being done by designers (cleverly labeled "design") 
 -  using the "v1" label to call out anything that is essential for releasing the site into the wild

**Comment by k88hudson** [comment]
Got it, thanks :+1:
