### ISSUE TITLE
url should not be required field on Clubs form

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#352]
Some clubs likely won't have a website, so let's make this field optional. 

Also, can we provide a more useful error message for field validation. e.g. "Please enter a web address that starts with http:// or https://"

**Comment by toolness** [comment]
Heh heh, you caught me relying on the standard ol' HTML5 form validation. That input widget has `type="url" required` on it, which makes different browsers give different validation error messages :)

Making the URL non-required is super easy, but writing custom validation logic for that particular field is a bit harder. I was hoping I could get away with it since the Webmaker clubbers are so web-literate, but we can fix it up nonetheless!

**Comment by toolness** [comment]
Ok, I just made the URL non-required in the backend in https://github.com/mozilla/teach-api/commit/028d6524b3e6d1acfb6ad2e5826e3198640b7144. Still need to make it non-required in the front-end though, which will involve changing the form as well as the marker popups (their code currently assumes that every club has a website URL to display).

That said, I am curious how people are supposed to find out more about the club, if they want to get involved?

**Comment by hannahkane** [comment]
Good question. @iamjessklein had the idea of adding a link to the owner's Webmaker profile, which I think makes sense.

**Comment by toolness** [comment]
Ok, this has been fixed in #410, and I've filed #424 to address your concern about the error message/validation being friendlier, @hannahkane!
