### ISSUE TITLE
Set environment variable for GA

### ISSUE THREAD

**Issue by adamlofting** [mozilla/teach.webmaker.org#368]
On staging and production:

```
GA_ACCOUNT='UA-49796218-20'
```

**Comment by adamlofting** [comment]
Hey @toolness - I'm not sure who sets these environment variables up, so please reassign as needed.

**Comment by toolness** [comment]
hmmm, so alternatively, one thing we can do is actually *default* `GA_ACCOUNT` to the id you listed above, but allow folks to disable GA entirely by setting `GA_ACCOUNT='DISABLED'` or somesuch. That way we wouldn't have to worry about staging/prod configuration at all... unless it's really bad for devs to be using the above tracking ID during development?

**Comment by toolness** [comment]
Oh, another thing I like about defaulting GA to enabled for devs is that the tracking code gets exercised more frequently that way, In the spirit of [dev/prod parity](http://12factor.net/dev-prod-parity). It would be terrible if we thought that everything was good for launch, only for some funky bug in the GA code to break the site for everyone, which we couldn't see because we didn't enable GA during development!

**Comment by toolness** [comment]
Speaking of which, a test suite for the GA stuff would be neat, let me know if you're interested in learning about that. No worries if not.

**Comment by adamlofting** [comment]
For this, I don't mind the GA_ACCOUNT being in the codebase as a default (it's not a secret after all). 

I plan to move the GA methods into a separate module ( [ticket](https://github.com/MozillaFoundation/mofo-example-app/issues/53) ) and at that point I would love some help setting up a test-suite.
