### ISSUE TITLE
TEACHING ACTIVITIES: Add banner photo

### ISSUE THREAD

**Issue by iamjessklein** [mozilla/teach.webmaker.org#473]
To be consistent with the parent pages, this page should have a "hero" image.

**Comment by sabrinang** [comment]
some photos that may work as teaching activities banner photo (dark center gradient photo treatment):

![screen shot 2015-04-06 at 2 37 57 pm](https://cloud.githubusercontent.com/assets/2492510/7013002/a5797e30-dc6a-11e4-957f-d82e84d61e1d.png)
![screen shot 2015-04-06 at 2 38 08 pm](https://cloud.githubusercontent.com/assets/2492510/7013004/a683f10c-dc6a-11e4-885d-7e9acb882e5e.png)
![screen shot 2015-04-06 at 2 38 20 pm](https://cloud.githubusercontent.com/assets/2492510/7013005/a831a238-dc6a-11e4-9125-f7ab01b33ef3.png)

**Comment by iamjessklein** [comment]
My preference is the middle image. 
Thoughts @vazquez @ldecoursy ? I like the center gradient treatment.

**Comment by vazquez** [comment]
If you are going for a gradient, I would make it a radial gradient. Right now there are clear edges of where the gradient ends (the guy's shirt on the 3rd option shows it clearly). I would also Multiply the gradient, so that it allows colour to blend in, as it feels like a black brush overlayed on top of the image at the moment.

Good selection of photos. In terms of composition, I think the 3rd one works best. However, the 1st one looks good because of the appropriate use of depth of field. The 2nd one I like for it's brightness, but I find compositionally challenging. It would be nice to focus the image on what the kids are making, but its hard because the persons on the corners are standing. The image also has a shallow depth of field which makes for a more complex than needed scene.

**Comment by hannahkane** [comment]
I like the third image best. @ldecoursy - do you have a preference?

**Comment by ldecoursy** [comment]
I like the third image too.

**Comment by sabrinang** [comment]
Great, I will use the third image and this photo will be treated and added to #471. Closing this bug.

**Comment by sabrinang** [comment]
Note: I smoothed out the linear gradient and added a subtle blur to the center. I tried the radial gradient but isn't as versatile on mobile when the photo shifts horizontally.
![herobanner-teaching-activities](https://cloud.githubusercontent.com/assets/2492510/7036218/80dadd30-dd46-11e4-82fb-b57c32a422ad.png)
