### ISSUE TITLE
CLUBS: Location too specific?

### ISSUE THREAD

**Issue by acabunoc** [mozilla/teach.webmaker.org#526]
The list only lets me select from either M4H or M5C postal codes -- which are two very specific locations in Toronto. Should I be able to have a generic Toronto located club? 

![screen shot 2015-04-01 at 15 25 58](https://cloud.githubusercontent.com/assets/617994/6949623/802e5bea-d883-11e4-96f9-8ea72179bf73.png)

Toronto M4H:

![screen shot 2015-04-01 at 15 30 20](https://cloud.githubusercontent.com/assets/617994/6949713/0e0a8632-d884-11e4-80b2-42055888e922.png)

**Comment by acabunoc** [comment]
#411

**Comment by hannahkane** [comment]
Similar problem from @ldecoursy: I added a club (using Firefox for Android). When entering location, I first started entering "Brooklyn" but it only populated with one option in a specific zip code that wasn't mine. I then added correct zip code but it didn't connect with city name, so it now reads strange in the overall list of clubs.

**Comment by hannahkane** [comment]
@toolness - and so the geocoding challenges begin! Let's discuss options at tomorrow's stand-up.

**Comment by toolness** [comment]
Rad!

Is there a separate issue filed about the problem we talked about in the stand today, where e.g. it's actually impossible to enter certain locations like "Springfield, Oregon" because it's not listed in the autocomplete suggestions after typing the word "springfield" but then typing anything more specific ("springfield o", "springfield,o", etc) yields no results?

At a technical level that's actually a different problem than the one addressed in this issue... this issue is about the search results being too specific--which actually may not be *that* hard to fix--but the other one is more about it being impossible to make a location *more* specific.

**Comment by hannahkane** [comment]
Just filed a separate issue. #554

**Comment by toolness** [comment]
Awsm!

I'm thinking that the solution for this issue will involve coalescing places with the same name, state/province and country into a single entry, and removing the zipcode and street information. Because the data Mapbox is giving back to us is actually [quite rich](https://github.com/mapbox/carmen/blob/master/carmen-geojson.md), that hopefully shouldn't be too hard.

My only concern is that we not accidentally coalesce places that are *actually* different--for example, there are apparently [at least 6 Springfields in Wisconsin](http://en.wikipedia.org/wiki/Springfield,_Wisconsin) and we wouldn't want those to get coalesced.

**Comment by toolness** [comment]
Ok, in PR #570 the interaction now looks like this:

![geocoding](https://cloud.githubusercontent.com/assets/124687/6982696/3109c3e0-d9e3-11e4-94e4-e13d887e12c2.gif)

Yay!

**Comment by ldecoursy** [comment]
:trophy:

**Comment by davidascher** [comment]
People interested in this issue might be interested in
http://www.mapcode.com/, which aims to provide geocoding for places which
don't have great postal addresses.

Practical question: wouldn't it be reasonable to start with the location
yielded by
https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/getCurrentPosition
?

**Comment by toolness** [comment]
Thanks David! Regarding using the geolocation API, I think there's actually a bit of a usability concern there, which is that we--er, the browser--actually needs to present the user with a choice:

<img src="http://www.developer.com/imagesvr_ce/3006/Figure01.png">

For me personally, this always causes the slightest amount of anxiety and distraction as I weigh the pros and cons between giving out my personal information to the website.

For a site like Yelp or a weather site, where the user's current location is closely tied to the core functionality of the app, I think geolocation is a great idea, and the user prompt is definitely worth the advantage of not constantly having to enter one's location... and if we plan on using the user's current location for other core functionality on the teach site, I'd say we should use it. But if the add club modal is the *only* place we're using geolocation, I think we should consider the possibility that using the API doesn't necessarily make things easier for the user, but rather forces them to make a decision that's potentially harder than just typing the name of the city they're in.

**Comment by davidascher** [comment]
Yup, its not a great ux, but neither is filling in a text box.

We could maybe do it in response to a "locate me" button (as in map
systems) as opposed to the usual onload prompt.

Anyway, a thing to keep in mind when doing user testing.
