### ISSUE TITLE
"Create an account" in nav needs to link to something

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#531]
Not sure whether we should hook it up to Persona at this point, or wait for login, so @toolness, please hold off for now, unless it's really trivial to hook up to the Persona sign-up experience.

**Comment by toolness** [comment]
Nope it's hard because we can't *just* send them to the Persona sign-up experience... because we ultimately link their account to their webmaker account, they actually need to create *both* a webmaker account *and* a Persona account, and both accounts need to have the same email.

So this is part of why the new login experience is going to be sooooooo much better. :)

**Comment by hannahkane** [comment]
Hmm...did not realize this. This means launching the site *is* dependent on login, which is counter to what I'd said before.

**Comment by hannahkane** [comment]
Will keep this ticket open just as a reminder, even though it's covered in the id.webmaker.org tickets. :)

**Comment by toolness** [comment]
Yeah, sorry I didn't emphasize this when implementing the Persona-based solution... I was under the impression that most of our users during the soft-launch would already have webmaker accounts from the olden days when we exclusively used Persona for login. I should have made that more explicit.

**Comment by toolness** [comment]
This is now kind-of subsumed by #576.

**Comment by hannahkane** [comment]
OK, closing this then.
