### ISSUE TITLE
TEACH LIKE MOZILLA: new copy for the middle CTA

### ISSUE THREAD

**Issue by iamjessklein** [mozilla/teach.webmaker.org#544]
- [ ] Rename the "Learn" CTA to "Understand"
 - [ ] Change sub-copy to "Learn more about the Web Literacy Map"

**Comment by LauraHilliger** [comment]
to clarify – I would both rethink the "learn" action on Teach Like Mozilla page and link to the web literacy map from the Teaching Activities page (and in that context "learn about web literacy" makes more sense to me.)

**Comment by hannahkane** [comment]
@LauraHilliger - what word would you recommend for the CTA on the Teach Like Mozilla page. What about  "Get Context" or "Deepen Your Understanding" (too long?) We could use "Explore," but that's a little weird since that's one of the sections of the Web Lit Map itself. :)

Creating a separate ticket for your point about the Teaching Activities page.

**Comment by LauraHilliger** [comment]
what about "Understand" and then "Learn More about the Web Literacy Map"? I like "Get Context" too, but worry that it's jargony.

**Comment by jgmac1106** [comment]
Change the world.
Empower others.
Lead. Learn. Teach.

**Comment by hannahkane** [comment]
Let's go with "Understand" and then "Learn more about the Web Literacy Map". I like that because I think it fits best with the other two CTAs on the page ("Listen" and "Say Hello").

**Comment by hannahkane** [comment]
Updated the first comment to reflect the decision.
