### ISSUE TITLE
LANDING: "Join" button copy and CTA should be rethought 

### ISSUE THREAD

**Issue by iamjessklein** [mozilla/teach.webmaker.org#545]
Right now the call to action is a bit ambiguous - the main CTA is "Unlock opportunities for all citizens of the Web," and then directs users to click the "Join us" button. It's unclear to me what I am joining and what the value is for me to actually Join. As far as I can tell the only action that I can perform exclusively with login is adding your club to the map. I am thinking that for the time being we might want to promote that instead of a hippy dippy "join us" - we are movers and shakers. <insert snark>  Then, in the future, if we roll out more functionality, we should promote it more prominently in this space. 

![screen shot 2015-04-02 at 10 10 50 am](https://cloud.githubusercontent.com/assets/535012/6965567/906ede6a-d920-11e4-8b14-144aabed6ca0.png)

/cc @kevzawacki @ldecoursy

**Comment by KevZawacki** [comment]
Agreed. It might be as simple as updating the button copy and having it route to the Clubs map. Maybe replace "Join Us" with:

+ Start Teaching
+ Start a Web Club
+ Start a Club 
+ Find a Club
+ Connect With Others

**Comment by hannahkane** [comment]
OK, I have come around on this. :) I was originally against the idea of making the primary landing page CTA be about Clubs, since it is such a heavy lift. But since the v1 is really mostly about Clubs, I agree that it makes sense for now.

Looking forward to figuring out a lower-bar CTA eventually, though. :)

I think the copy needs to prevent surprises, so it should use similar language to what they'll find at the destination page. So, I'd vote for "Start a Mozilla Club" (which is I believe the term we're using now. I need to file a ticket to change the copy on the Clubs page itself to match.)
