### ISSUE TITLE
Can't enter certain locations

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#554]
e.g. it's actually impossible to "Springfield, Oregon" because it's not listed in the autocomplete suggestions after typing the word "springfield" but then typing anything more specific ("springfield o", "springfield,o", etc) yields no results

**Comment by toolness** [comment]
It looks like [geonames.org](http://www.geonames.org) might be an alternate provider for geo data.

**Comment by toolness** [comment]
Oh, I've got good news! It looks like the problem is just with our front-end code, and not the mapbox API (so we don't have to hunt for a new provider etc). I know this looks confusing to non-devs, but here's a network log of the response we're getting back from Mapbox when searching for "springfield oregon":

![2015-04-02_19-29-35](https://cloud.githubusercontent.com/assets/124687/6975789/ef5eebba-d96e-11e4-953a-a20f4f0b9541.jpg)

That information in the bottom-right pane is showing that Mapbox *is* actually returning us a single result containing the latitude and longitude of Springfield, Oregon! Our front-end code just isn't seeing it. Fixing that should be easy peasy.
