### ISSUE TITLE
Setup Analytics / Metrics for teach.webmaker.org

### ISSUE THREAD

**Issue by adamlofting** [mozilla/teach.webmaker.org#57]
* Project Requirements: @hannahkane @simonwex 
* Analytics Specification: @adamlofting
* Analytics Implementation: @simonwex or @adamlofting

The new teach.webmaker.org website needs analytics 'instrumentation' in order to understand how it is used.

This will mostly likely start with simple Google Analytics tracking of pageviews, but how we setup the Google Analytics account and tracking will depend on a number of strategic and practical issues.

### Requirements Questions:

Q's for @hannahkane: 
- [x] Is the domain name going to be `teach.webmaker.org`? (I've heard other possibilities mentioned)
- [x] Is this site viewed as part of the same user experience as webmaker.org and the tools, or as it's own "vertical"? My understanding is that this is a standalone experience we want to review independently of traffic to the learning app(s).
- [x] Do we have a concept yet of on site conversions? The success actions we want to optimize towards? (it may be to early for this)

Q's for @simonwex:
- [x] What tech stack are we using to build this? (in particular templating choices / frameworks)

### Other assumptions:
* We're not ready to start thinking about A/B testing (ie Optimizely) setup on this website.

**Comment by adamlofting** [comment]
p.s. @hannahkane could you assign this ticket to me please? I don't have the rights in this repo. :grin:

**Comment by hannahkane** [comment]
My best attempt at answering the questions in the description:
 * The domain will likely *not* be teach.webmaker.org. Right now @HPaulJohnson is thinking learning.mozilla.com, but I don't believe that's finalized.
 * I think you're right that this is a separate stand-alone experience, though there will be areas of overlap (notably, it will share a user authentication experience with Webmaker).
 * As I understand it, user acquisition is not in itself a main goal, at least not initially. Our KPIs are around activity in cities, as measured by Clubs (and Hives), so a primary metric will be # of cities with Clubs. Since "Add Your Club" is such a heavy lift, we will likely have lower-bar CTAs like "sign up" throughout (for example, on the homepage). We'll want to watch closely, and iterate on the onboarding experience (much like the learning product team has done). Other things we'll want to track to measure engagement include: clicks on curriculum modules, time on site, and return visits (30- and 90-day retention rates).

**Comment by adamlofting** [comment]
This is great thanks.
- [ ] Once we settle on domain name (once we settle on branding) Adam needs to setup a new GA property via MoCo for tracking this site

**Comment by adamlofting** [comment]
Question to discuss with devs as I'm going around in circles trying to add something really basic to these published HTML pages:

I want to add this into the template (ie every page)

```
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-59356678-3', 'auto');
  ga('send', 'pageview');
</script>
```

Ideally With the `UA-59356678-3` being a variable we can set in the config file.

### Things I have tried:

#### Route 1: Writing this as a JSX react component

And including this in `index-static.jsx`. I tried this, but you can't put that inline js script through JSX as it doesn't like semicolons etc... I couldn't find a way to render it as a literal.

There are ways to do this if the jsx component is loaded dynamically and firing events, but this doesn't translate to our static generation model.

#### Route 2: A seperate js file, and a simple footer include like we do on webmaker.org

https://github.com/mozilla/webmaker.org/blob/master/views/layout.html#L189

But it's not clear where I would put this js file in the project that it gets published to somewhere in the dist folder.

**Comment by adamlofting** [comment]
cc @toolness @alicoding @simonwex for the question above.

**Comment by toolness** [comment]
Ah, so to bust up route 1, in order to render the thing as a literal, you have to use React's funky [`dangerouslySetInnerHTML`](http://facebook.github.io/react/docs/special-non-dom-attributes.html) attribute, which I do here to quickly remove the `no-js` class from the page's root element on page load:

https://github.com/toolness/Mozilla-Learning/blob/master/lib/index-static.jsx#L21-L23

**Comment by adamlofting** [comment]
Ah, thanks! I'll work with that :+1:

**Comment by adamlofting** [comment]
I've opened a PR with an initial take on this.

But as it's bringing up some unusual challenges, I'd like to get a better overview of the engineering first. I've opened this up as a new discussion here: https://github.com/mozilla/teach.webmaker.org/issues/180

**Comment by adamlofting** [comment]
I've requested a new GA property for the domain name: teach.mozilla.org - once this is setup we can update the account id in the repo.

This can be tracked in [Bug 1141659](https://bugzilla.mozilla.org/show_bug.cgi?id=1141659)

**Comment by hannahkane** [comment]
@adamlofting - do we need to move this to the March 27th heartbeat?

**Comment by adamlofting** [comment]
Yes, thanks :+1:

**Comment by adamlofting** [comment]
The remaining items for this ticket are underway in the following issues:
- [ ]  Additional Analytics Instrumentation #362 
- [ ]  Set environment variable for GA #368
