### ISSUE TITLE
Add asterisks to indicate required fields on Clubs form

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#577]
This helps with the usability issue identified in #540.

**Comment by toolness** [comment]
So now that #540 is actually fixed, I'm wondering if we still need this?

Also, if we do still need it, I have questions about the design. For example, is just an asterisk next to the field label enough, or do should we also put a "* indicates required field" sort of message somewhere on the dialog? If so, what exactly should that message say, and where should it go? Alternatively, do we want to just put "(required)" next to the field labels instead of an asterisk?

**Comment by hannahkane** [comment]
I don't think we need this now that #540 has been resolved.
