### ISSUE TITLE
Rio: Review Laura's report with ITS

### ISSUE THREAD

**Issue by thornet** [mozilla/teach.webmaker.org#58]
Laura d. R. is finishing a report on Feb. 18 about her learnings from the LAN house visits. We need to meet with ITS to distill our learnings and roll that into our project plan.

**Comment by thornet** [comment]
Photos from Laura for easy reference: https://www.flickr.com/photos/laura_nk/sets/72157650483736818/

**Comment by soapdog** [comment]
Fantastic pics!

I took some pictures during the last day from Marco Lan House and Poubel Lan House, they are at

https://www.flickr.com/photos/soapdog/sets/72157648530634044/

https://www.flickr.com/photos/soapdog/sets/72157650785517126/

**Comment by soapdog** [comment]
Me and Mario are going to ITS tomorrow (26th of February). We're having a call with Ben, Michelle and others and decided that we could take the call from there.

We also have a schedule meeting at ITS on Monday to review the report.

**Comment by thornet** [comment]
Thanks, Andre! Is this ticket closed now?

**Comment by soapdog** [comment]
Not closed. First pass at translation was done but the changes were not integrated yet. We had a meeting yesterday and we're still digesting stuff. This will be ready shortly.

**Comment by soapdog** [comment]
@LauraReynal is closing the report and I will update the translation as soon as she OKs it (if there is any change). I just sent some extra photos taken by LH employees during the week to Laura, it took me a while to sort this out because the photo lab made lots of snafus with the material. Will close soon.

**Comment by LauraReynal** [comment]
Hey @thornet and @soapdog - from my side the work on the report is almost done. Bobby is doing a grammar pass and then we are ready to ship. 

I have not checked the PT translation obviously - I will let you sort it out. 

ITS has reviewed the English report - So from my end its good to close - I will let @thornet assess. 

Thanks 
Laura

**Comment by soapdog** [comment]
Laura,

I will need a pass on the PT translation to check for typos and grammar but I can arrange that here. Please let me know when you're done so that I can pick the file and look for changes.

Also before publishing the report, I would like to change the contact information and have my LDAP account and mozilla foundation email set up. In the report we have my personal email account and I would like to try to keep those things separate.

Cheers
andre

**Comment by LauraReynal** [comment]
Of course, I have no idea when your foundation email will be ready - I
think @benrito can help us identify times. Let us know Ben so that I can
change Andre's and Mario's addresses in the report

*Laura de Reynal*
Webmaker - Field Research
@lau_nk <https://twitter.com/lau_nk>
Skype: laura-dereynal

**Comment by thornet** [comment]
@soapdog is this one ready to close?

**Comment by soapdog** [comment]
This is closed ;-)

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/28"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/28.
Please don't comment on it here.
