### ISSUE TITLE
Change instances of "Mozilla Web Clubs" and "Web Clubs" to "Mozilla Clubs"

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#618]
on /mozilla-web-clubs/:
 - [ ] Change "Mozilla Web Clubs" in header image to "Mozilla Clubs"
 - [ ] Change "How do Web Clubs work?" title to "How do Mozilla Clubs work?"

**Comment by toolness** [comment]
Ok, this was fixed in #652, which I just merged, but I just noitced that the URL path for the page is still `/mozilla-web-clubs/`. Should it be changed to `/mozilla-clubs/`, or perhaps even just `/clubs/` to make for an easy-to-remember URL (and one that doesn't need to change if we decide to rename yet again)?

**Comment by ScottDowne** [comment]
@toolness Yeah, I think the url should be updated. An argument could be made that it should just be "clubs".

On top of that, http://teach.mofostaging.net/clubs/curriculum/ and http://teach.mofostaging.net/clubs/curriculum/ might also be wrong. It has it as just "clubs"

**Comment by hannahkane** [comment]
+1 to changing it to /clubs

**Comment by jgmac1106** [comment]
Another name change. Today must end in "y"

**Comment by hannahkane** [comment]
hey @ScottDowne - did we end up changing the path to /clubs? 

cc @secretrobotron

**Comment by secretrobotron** [comment]
On staging, /clubs goes to a page that looks pretty broken. We just landed some code that points to /mozilla-web-clubs.
