### ISSUE TITLE
[MIGRATED] Create spreadsheet for counting "active" cities

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/teach.webmaker.org#647]
Based on https://github.com/MozillaFoundation/plan/issues/395 we need to create a spreadsheet that Regional Coordinators and MLN staff can use to help us count/track "active" cities until a more automated solution is available. 

I'll start a draft and share here for input.

cc @hannahkane @thornet @amirad @simonaramkisson @soapdog @adamlofting

**Comment by ldecoursy** [comment]
Here's a first take: http://bit.ly/1aX85Q0, to be discussed during RC call on Wednesday, then with @adamlofting on Thursday

**Comment by ldecoursy** [comment]
@adamlofting is thinking through how we can better log individual activities (separate but connected tab in the spreadsheet for now)

Also looking at how we collect/report this data in three phases:
* Our team works with this spreadsheet for next three weeks inputting what we know
* Share on first RC kick-off call in first week of May, get feedback and determine reporting mechanism that works best for them and gets us the info we need
* In the future, the events and clubs tools collect this in a more automated way

@thornet @hannahkane @adamlofting LMK if I'm missing anything

**Comment by thornet** [comment]
+1 and adding @soapdog to review and weigh in with how he'd like to track his clubs. Good proto-RC feedback. ^^

**Comment by soapdog** [comment]
Thanks for adding me. Due to the diversity of possible Webmaker events, I believe that we should approach the metrics a bit more like the Mozilla Reps program. All the spreadsheet is kept but we also add columns where the event owner can add his desired metric of success and what happened. An example would be something like: "Having 10 makes made" and the outcome could be a number such as "15". Or things such as "Having 50% woman to men ratio in the event" actual outcome "75% woman 25% man".

I am asking for this because different events may have different objectives and without this owner defined metric its hard to differentiate between events and measuring success. In the current spreadsheet the only thing we have for measuring the events is attendance. Owner defined metrics give them agency over the process which I think is a good thing.

This tracking effort can be used for more than only tracking what is happening it can also track how well things are happening which is a great opportunity for acquiring more intelligence about our programs.

**Comment by adamlofting** [comment]
I've split the current tab in the spreadsheet into two:

1. Project Directory
2. Project Activity Log

When you add an item to the activity log, the project title gives you a drop-down menu from the Directory sheet so you can match the activities to the projects. 

This format will work for long-term reporting of Active Cities metrics, but let's spend a little time adding events in this format, and see how it works for recording.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/121"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/121.
Please don't comment on it here.
