### ISSUE TITLE
Link at top of event resouces page need to be fleshed out more

### ISSUE THREAD

**Issue by ScottDowne** [mozilla/teach.webmaker.org#649]
Right now they are simple links, and before I forget, we need to fix these up.

They also need design, I believe. Ricardo told me not to do the ones in the UI comp so he might have more context.

@vazquez

**Comment by iamjessklein** [comment]
Let's use what is in the original mockup for Inspector Gadget and then file issues against those.

**Comment by hannahkane** [comment]
+1

**Comment by iamjessklein** [comment]
@ScottDowne or @toolness do you have the design assets from @vazquez ?

**Comment by mmmavis** [comment]
Updates on this?  :grin: let me know how I should proceed.

**Comment by hannahkane** [comment]
pinging @vazquez to provide assets and guidance. :)

**Comment by mmmavis** [comment]
seems like this is something we can do in this heartbeat :+1:

**Comment by hannahkane** [comment]
Just trying to re-wrap my head around this ticket. 

I believe we're talking about these links at the top of /events/resources:

![screen shot 2015-05-01 at 1 59 35 pm](https://cloud.githubusercontent.com/assets/8389648/7437234/b8ea4d74-f00a-11e4-92dc-f827bb44bdea.png)

I don't think we actually need to implement the design as originally mocked up here:
![screen shot 2015-05-01 at 2 03 13 pm](https://cloud.githubusercontent.com/assets/8389648/7437256/da980538-f00a-11e4-94db-7feda0bb5b01.png)

Because the copy in those mouseover expansions doesn't actually seem necessary.

I think we need a different, simpler solution that makes it clear that those are anchor links. We could simply make it a line-separated list, and add a "Jump to:" title.

@sabrinang or @iamjessklein - could one of you assign this to yourself and propose a new solution?

**Comment by vazquez** [comment]
I think we should keep the all caps treatment, but instead of displaying it across let's just display it as a normal bullet point.

- EVENT GUIDES
- LOGOS & ASSETS
- EVENT DETAILS
- EVENT SUPPORT

**Comment by iamjessklein** [comment]
@sabrinang - can you take a look into the UI here?

**Comment by sabrinang** [comment]
![event-resources-bullet-styles-ideas](https://cloud.githubusercontent.com/assets/2492510/7460290/b257c72c-f256-11e4-92da-4e61024cf71d.png)
Yeah - I like the all caps treatment and I mocked up various bullet styes and I quite like the caret style.

**Comment by vazquez** [comment]
My favourite is the caret style :+1:

**Comment by iamjessklein** [comment]
+1  :+1: 

@mmmavis should this be re-assigned for implementation?

**Comment by mmmavis** [comment]
@vazquez @iamjessklein (@sabrinang is on PTO currently)

Sorry I can't really tell but is the caret an image? ionicon? font awesome? or triangle drew by CSS?

**Comment by vazquez** [comment]
@mmmavis - Looks like ionicon `ion-arrow-right-b`

**Comment by mmmavis** [comment]
Thanks @vazquez :sun_with_face: 

Realizing that we are [using Kate's ionicons](https://github.com/mozilla/teach.webmaker.org/blob/develop/package.json#L47) and `ion-arrow-right-b` is not included in that set.  Can we use `ion-android-arrow-dropright` instead or @k88hudson can I submit a request for including `ion-arrow-right-b`?

**Comment by vazquez** [comment]
I think for this case it would be okay to use `ion-android-arrow-dropright`
:)

**Comment by k88hudson** [comment]
@mmmavis it's possible if you need to in the future :)

**Comment by mmmavis** [comment]
qooool thanks @vazquez @k88hudson
