### ISSUE TITLE
Video says "activate Adobe Flash" on latest Firefox, which supports HTML5 video

### ISSUE THREAD

**Issue by toolness** [mozilla/teach.webmaker.org#696]
I'm not sure if it's the default, but I have my plugin preferenes to not load Adobe Flash content unless I give it permission:

![2015-04-15_8-33-06](https://cloud.githubusercontent.com/assets/124687/7158713/bb1e1b9c-e34a-11e4-9511-8dcbf39267d4.jpg)

This means that the video on the events page looks like this in my browser:

![2015-04-15_8-35-28](https://cloud.githubusercontent.com/assets/124687/7158717/c7aca90a-e34a-11e4-8fa8-296a13d4f519.jpg)

This seems suboptimal, since my browser does support H264-based HTML5 video via the `<video>` tag.

I don't think it's that big a deal if I'm an edge case--after all, I could just click "Activate Adobe Flash" to see the video--but it is bad if there is *no* HTML5 fallback, since that means that devices without Flash (like iPhone/iPad) might not be able to see the video at all.

**Comment by mmmavis** [comment]
@toolness 

According to [YouTube's blog post](http://youtube-eng.blogspot.ca/2015/01/youtube-now-defaults-to-html5_27.html) they have now made HTML5 player the default player when embedding using `<iframe>`

I didn't have any plugins on FF to prevent flash from playing and I was wondering why my YouTube embed was still played by Flash by default.  It turns out we have to [**manually toggle** the option](https://www.youtube.com/html5).  Is it the kind of fallback you were looking for?

**Comment by toolness** [comment]
> It turns out we have to [**manually toggle** the option](https://www.youtube.com/html5) to set HTML5 player as default.  Is it the kind of fallback you were looking for?

Ah, ok, that seems silly that YouTube requires end-users to opt-in to the HTML5 player, but whatevs. It looks like YouTube will do the right thing on iOS regardless, so that's good.

Thanks for investigating, mavis--closing the issue now!
