### ISSUE TITLE
Do a trial run of jekyll-style markup for exisiting curriculum

### ISSUE THREAD

**Issue by davidascher** [mozilla/teach.webmaker.org#72]
Goal: to test with @thornet et al. whether editing markdown files with some advanced features like tags in front matter feels workable (as opposed to raw HTML).

Sub-tasks:

- [ ] Pick 2-3 bits of curriculum to templatize, to understand what's generic and fits in a template, and what's specific to a specific bit of content
- [ ] make a template (using Jekyll, or Hugo, or Harp… -- specific doesn't matter too much at this stage, and make a new repo with that template
- [ ] port the picked bits of curriculum to markdown (suggest using http://domchristie.github.io/to-markdown/ for a quick pass
- [ ] show @thornet and walk her through an editing process

**Comment by LauraHilliger** [comment]
Some quick thoughts that might influence this:

We templatized curriculum through the teaching kits, so you may be able to save a step and take a look at what everything has in common. In that regard the KitBuilder might be the fastest way to understand general vs specific components in curriculum: http://kitbuilder.webmakerprototypes.org/ 

Training used jekyll + markdown, and I actually went back to HTML because I needed more control over layout and styling. I would guess that our team would prefer the flexibility (sometimes we don't have time to wait for design/dev resources).

Emma Irwin is playing around with an instance of course in a box (from P2PU built w/ jekyll, the thing that training was prototyping) in which she's modified it to separate content and platform. So she has the [infrastructure](https://github.com/emmairwin/reps-edu/) repo as completely separate from the [content](https://github.com/emmairwin/community_curriculum) which, in our case, would make contribution easier for non-devs (e.g. finding the place in jekyll where the content lives when you aren't devvy is tricky and frustrating).

Happy to give you thoughts on my experiences as a non-dev slash actually pretty devvy if it helps you at all.

**Comment by davidascher** [comment]
Super useful, thanks Laura.

Note: many markdown processors let you just use HTML blocks when needed.
It may not be enough (especially given if you need a lot of styles applied
on a per-div basis), but good to know in case you didn't.

More critical than markdown vs. HTML is the notion of 'front-matter', which
can be parsed by the site generator to do things like detect tags, ordering
of pages, etc.  Impossible to do without building custom concepts in HTML
AFAIK.

**Comment by thornet** [comment]
+1 to looking at Emma's setup as possible inspiration: https://github.com/emmairwin/reps-edu/

@jbuck: here are some example activities to play with: 

* http://mozilla.github.io/webmaker-curriculum/WebLiteracyBasics-I/session01-kraken.html
* http://mozilla.github.io/webmaker-curriculum/WebLiteracyBasics-I/session02-puzzlebox.html

**Comment by LauraHilliger** [comment]
storing the conversation on simplifying jekyll in case...uh, in case the conversation is somehow useful: https://github.com/mozilla/webmaker-curriculum/issues/32

**Comment by hannahkane** [comment]
@davidascher - can we close this ticket for now? I think a version of it will be re-opened when we're ready to add editing functionality to the curriculum pages.

**Comment by hannahkane** [comment]
Closing this for now.
