### ISSUE TITLE
"Invalid state" after resetting password

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/teach.webmaker.org#735]
@edrushka and I just ran into an "Invalid State" error on teach-api.herokuapp.com after resetting her password and trying to log in with new credentials.

**Comment by toolness** [comment]
Is that reproducible anytime anyone resets their password?

**Comment by hannahkane** [comment]
I was just able to successfully reset my password and log in with it.

**Comment by secretrobotron** [comment]
I'l try right meow.

**Comment by secretrobotron** [comment]
Yeah, can't seem to repro atm. No logs, @toolness ?

**Comment by toolness** [comment]
Nope, "invalid state" isn't actually an internal server error--it just means that the [`state` parameter passed to the OAuth2 callback](https://github.com/mozilla/id.webmaker.org/blob/develop/docs/oauth.md#2-webmaker-redirects-back-to-your-application) doesn't [match](https://github.com/mozilla/teach-api/blob/master/teach/views.py#L87-L88) what's stored in the user's server-side session.

It could be caused by any number of things external to the server--it just means that somewhere in between the time that teach-api forwarded the user to [id.webmaker.org's OAuth authorize endpoint](https://github.com/mozilla/id.webmaker.org/blob/develop/docs/oauth.md#1-redirect-users-to-request-access) and the time that id.webmaker.org sent the user back to teach-api, the `state` argument passed to the callback wasn't what it was expected to be.

That said, there's some things we could do:

* Add some metrics to track how often this is happening. If it's happening a lot, then we should really look into this more.
* Add some fault tolerance so that users are presented with something a bit more helpful than an inscrutable error message on a completely unfamiliar website. For instance, directing the user back to the teach site with some kind of message like "sorry, an error occurred when trying to log you in; please try again." could be more helpful.
* Instead of storing `state` as an opaque token that is looked up in the user's server-side session, we could have it be a meaningful value [signed](https://docs.djangoproject.com/en/1.8/topics/signing/#using-the-low-level-api) by teach-api. This could reduce the possibility of certain kinds of errors occurring, though it could also make login less resilient to certain types of attacks if we don't do it properly.

**Comment by secretrobotron** [comment]
1 and 2 sound like good things to do right away. Obviously, this problem shouldn't happen (and is, in fact, hard to reproduce), so some metrics will make it easier to see when and how it happens. And :+1: much better to direct user back to teach with error message.

**Comment by toolness** [comment]
@jbuck just mentioned to me on IRC that @edrushka may have had multiple browser tabs open. If she initiated login in tab A without completing it, then initiated login in tab B without completing it, and then completed login in tab A, the "invalid state" message would appear, because her session cookie would expect the `state` value set by tab B but receive the `state` value set by tab A.

I think my solution (3) would fix this, but we'd have to be very careful to avoid creating replay attack vulnerabilities and such. Alternatively, since it's probably rare, we could potentially just live with the error, using the metrics provided by (1) to make sure it's not *too* common and the UX provided by (2) to make sure we don't totally lose users.

**Comment by secretrobotron** [comment]
:+1: good idea

**Comment by edrushka** [comment]
I am innocent! I only had one browser tab open! However, Bobby and I were mucking around quite a bit trying to break things, so it's unlikely any will reproduce my exact steps.

**Comment by toolness** [comment]
Hahaha ok, thanks for the explanation erika :)

So to summarize, we'll go with the following solution, which I will create new issue(s) for.

When the "invalid state" error occurs, we:

1. Log this in some useful way, to keep an eye on how often it's happening to people.
2. Redirect the user back to the teach site, passing it some information (e.g. `?loginerror=yup`) informing it that login failed, at which point it will inform the user in a friendly way.

If our metrics from (1) indicate that the error is happening more often than we'd like, we'll look into more rigorous solutions.

**Comment by secretrobotron** [comment]
:+1: where should we log that? Could use GA, but not sure if that's abusive. @adamlofting ?

**Comment by toolness** [comment]
Yeah, that's a good question. I was thinking we could actually do the steps in reverse order, so that the logging would happen via GA on the "login error" page on the teach site. If that is abuse of GA though we can figure out something else... How are we doing back-end error logging these days?

**Comment by toolness** [comment]
Ok, so in https://github.com/mozilla/teach-api/commit/b2f21e2097aefbce318e16224d6fe02e9b40402b I've made things at least a *tiny* bit more user friendly by adding a link back to the teach site and telling the user to try again:

![2015-04-21_3-29-49](https://cloud.githubusercontent.com/assets/124687/7247360/c734b13a-e7d6-11e4-9228-ca5175a587f3.jpg)

You can view that page "live" at https://teach-api.herokuapp.com/auth/oauth2/callback?code=invalid&state=invalid.

Obviously it's still suboptimal but I'm thinking for v1, we can just add GA to this page, and if we get lots of hits we can make the error more user-friendly (by redirecting directly to the teach site w/ an error message shown on it) or jump straight to [option 3](https://github.com/mozilla/teach.webmaker.org/issues/735#issuecomment-94547369).

**Comment by adamlofting** [comment]
That's a perfectly valid use of GA. :smile: 
We just need to choose if the error is 'more' a teach.m.o error, or 'more' a login.w.o error and use the corresponding GA account details to log the error there.

**Comment by toolness** [comment]
Cool! I think it is 'more' a teach.m.o error, since the page would ideally be hosted *on* teach.m.o. (and we might move it there once we've implemented #585).

**Comment by toolness** [comment]
Ok, since we're using newrelic for server-side monitoring, it was easier to just add the metrics tracking via newrelic instead of GA, which I did in https://github.com/mozilla/teach-api/commit/c085f24eff3a672c1a8af880eb957a7e6c734af7.

**Comment by toolness** [comment]
At this point there isn't really much to do aside from just watching the metrics to see if oauth2 handshake problems like this occur unreasonably often.

**Comment by adamlofting** [comment]
That works for now, but we won't have NewRelic much longer as it's too expensive for us.

**Comment by toolness** [comment]
Oh, um, I am just using the free plan. I guess it kind of sucks since it only keeps metrics around for 1 day though.

**Comment by hannahkane** [comment]
@toolness - Are we okay to close this ticket now?

**Comment by toolness** [comment]
Yup I think so!
