### ISSUE TITLE
Can't make clubs success modal go away

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#745]
Firefox 37

Neither the "x" nor the "Take me to my Club" button nor clicking outside of the modal made it disappear.

**Comment by toolness** [comment]
So my theory here is that this is due to #712 and React's `CSSTransitionGroup` being apparently wonky with Firefox, as I mention in https://github.com/mmmavis/teach.webmaker.org/pull/1#issuecomment-93989189. If it was wonky in such a way that the "transition complete" code never fires on modal close, it'd mean that the modal would never be removed from the DOM, I think. It's just a theory, though.

It's also possible that the wonkiness is logged as a bug in React somewhere, and it's also possible that perhaps it's fixed in React 0.13.

**Comment by toolness** [comment]
Hmm, it seems there are multiple [`CSSTransitionGroup`-related issues](https://github.com/facebook/react/search?q=CSSTransitionGroup&type=Issues&utf8=%E2%9C%93) filed in GitHub. I guess I recommend, regrettably, backing out #712 and seeing if this problem goes away. :/

**Comment by hannahkane** [comment]
K. let's try it.

**Comment by mmmavis** [comment]
I also discovered the "Add Your Club" modal is the *only* modal that's having problem with closing.  It throws console error `"transition(): tried to perform an animation without an animationend or transitionend event after timeout (5000ms). You should either disable this transition in JS or add a CSS animation/transition."` when you try to close that modal.

Googled a bit and found a potential solution mentioned in https://github.com/facebook/react/issues/1707#issuecomment-66860858.  I'm gonna try integrating [TimeoutTransitionGroup](https://github.com/Khan/react-components/blob/master/js/timeout-transition-group.jsx) and see if it fixes the problem.

**Comment by toolness** [comment]
@hannahkane, this should be fixed w/ the landing of #747 (haha get it?). Travis is taking a long time to get the latest version on teach.mofostaging.net (you can see what revision it's on through the "dev version" ribbon/modal) but once it finally does, things should work! Please re-open this ticket if they don't.

**Comment by hannahkane** [comment]
Good joke. :)

Will do.

:airplane:
