### ISSUE TITLE
Location for work related to Club Captain and Regional Coordinator Pathways 

### ISSUE THREAD

**Issue by soapdog** [mozilla/teach.webmaker.org#748]
We should start experimenting with content for the Club Captain and Regional Coordinator pathways but I am not sure where to place it. Do we create a new repo for it or since the content is basically in booklet format should we use Google Docs?

I want to start iterating over possible indexes or content structure with the team but I am not sure where to place it. I don't think that Etherpad is the best location for such content.

My recommendation is to use a workflow like GitBook (https://www.gitbook.com/) where Markdown files in a github repo are used to generate the booklets. It would make it very easy to experiment with content.

**Comment by LauraHilliger** [comment]
@soapdog I set up a google doc folder b/c github is too high bar for people. Since RC and CC content is heavily related to Teach Like Mozilla, I've worked out pathways that use TLM content (in addition to new stuff).

The content folder is here: https://drive.google.com/drive/u/1/#folders/0B0u8434q8_LPNTJlejh4YWhWRkk/0B0u8434q8_LPfkVzUlRuMVZ4MmxIb0dKc01ueEs3MW9uREFUb2RYdWJKeEFTcGRYX2ppM1U

and in github all the issues are labeled with "curriculum" and "leadership": https://github.com/mozilla/teach.webmaker.org/issues?utf8=%E2%9C%93&q=is%3Aopen+label%3Acurriculum+label%3Aleadership

**Comment by thornet** [comment]
The Google folder seems like a great place to gather docs and organize. Wonder if it's worth testing Gitbook or something similar as a way to display the docs once they're gathered and collated.

**Comment by LauraHilliger** [comment]
+1 Andre and I are going to talk about this today. We have both the gitbook and course in a box options, but @hannahkane also filed #457 so we have multiple ideas - need to be strategic and true to the content

**Comment by LauraHilliger** [comment]
talked to Andre. We will use the Drive folder for now with the aim of transferring to teach.mozilla.org once #457 is worked out. If we are ready to launch/publish content beforehand, we will decide between gitbook and course in a box.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/learning-networks/issues/138"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/learning-networks/issues/138.
Please don't comment on it here.
