### ISSUE TITLE
Implement homepage redesign

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#856]
Pending completion of #800 

Important: the blog feed should be limited to articles tagged with "#teachtheweb" rather than the entire blog feed.

**Comment by hannahkane** [comment]
Estimation effort: small

**Comment by hannahkane** [comment]
No longer blocked!

**Comment by ldecoursy** [comment]
@sabrinang to follow-up with Cassie for R+

**Comment by mmmavis** [comment]
For blog posts: 

We want to show the latest posts tagged with **#teachtheweb** on blog.webmaker.org
RSS feed url: https://blog.webmaker.org/tag/teachtheweb/feed

**Comment by toolness** [comment]
Ok, there's a few things we can do to get those posts:

* Modify the Wordpress RSS feed to be [delivered with CORS headers](http://stackoverflow.com/questions/12517039/how-to-add-cors-support-to-wordpress-rss2-feed). I'm not actually a huge fan of this because that RSS feed is actually quite large, as it includes the entire post. It's also including the 10 most recent posts, while we only need to show the 4 most recent posts on that homepage.
* Use one of the WordPress APIs with CORS headers. I'm unfamiliar with all the different plugins and APIs that are available; many of them don't support CORS out-of-the-box.
* Wait until we have #585 done and have the lightweight dynamic server pull from the Wordpress RSS feed.
* Have the static site generator pull from the Wordpress RSS feed and statically include it in the generated HTML for the homepage.
* Add an endpoint to teach-api that pulls the Wordpress RSS feed, minimizes it to include only what's needed for the homepage, and delivers it as JSON with CORS headers to the teach site.

Given those options, I think the last one (adding an endpoint to teach-api) may actually be the most straightforward and efficient option, as it's not very technically volatile, can be implemented relatively quickly, and will also work well once we move to a dynamic server situation.

**Comment by toolness** [comment]
@mmmavis, regardless of which one of the above sol'ns we go with, I don't want it to block you on implementing the rest of the page. Want to just use dummy JSON data for now, and we'll replace it with the real data once we figure out exactly how we want to proceed?

**Comment by toolness** [comment]
Oh wait! Yet another option is to just use the [Google Feed API](https://developers.google.com/feed/v1/devguide), at least for now. Hmmmmmm

At the very least I think it might be smart to use the same [JSON schema](https://developers.google.com/feed/v1/reference#resultJson) that the Google Feed API uses. As long as we use that, we can plug-in whatever actual implementation we want--whether it's a same-origin Ajax request to a lightweight dynamic server, a CORS request to teach-api, the Google Feed API, or something else entirely.

**Comment by mmmavis** [comment]
Cool, I like this (temp) solution.  How about I use Google Feed API for now and when we have the teach-api endpoint ready (OR dynamic server ready) we will swap to it.

**Comment by toolness** [comment]
Ok, sounds good!

**Comment by mmmavis** [comment]
(Note)
Use this [.ai file](https://drive.google.com/a/mozilla.com/file/d/0B4Q8pzCpDS_eVzBPXzNfb3ZfQkk/view?usp=sharing) instead if using AI CS6 to open.

**Comment by mmmavis** [comment]
@sabrinang as mentioned in https://github.com/mozilla/teach.webmaker.org/issues/800#issuecomment-105756502, please help export some svgs for the hero unit buttons!  :wink:

**Comment by mmmavis** [comment]
Actually, if we are changing icon color on hover state(yellow button on screencap below), we can probably use CSS sprite tricks to achieve that.

@sabrinang ,@toolness thoughts?

**Comment by sabrinang** [comment]
![hostanevent-hover](https://cloud.githubusercontent.com/assets/2492510/7829807/16cde08c-03fb-11e5-87a4-43fa13417c1f.png)
![hostanevent](https://cloud.githubusercontent.com/assets/2492510/7829806/16cc6c66-03fb-11e5-9f81-510e83f1d571.png)
![startamozillaclub-hover](https://cloud.githubusercontent.com/assets/2492510/7829810/16cfe9e0-03fb-11e5-9ca0-94f9e447f7c8.png)
![startamozillaclub](https://cloud.githubusercontent.com/assets/2492510/7829809/16cfeab2-03fb-11e5-9a7a-d96e4e025f3c.png)
![teachanactivity-hover](https://cloud.githubusercontent.com/assets/2492510/7829808/16ce493c-03fb-11e5-9cfa-474c4c2a1c39.png)
![teachanactivity](https://cloud.githubusercontent.com/assets/2492510/7829811/16d1b036-03fb-11e5-92df-9a794c2dd515.png)







I exported the .svg in blue and grey (hover) in case it can not be achieved in CSS:
https://drive.google.com/a/mozilla.com/folderview?id=0B4Q8pzCpDS_efl9IT3FaODEwNzZ1VndYSFhUYXlFcG43MUR6ZncyVFJUQ20yTDFOWTIyUWM&usp=sharing

**Comment by mmmavis** [comment]
hey @sabrinang if you could export the files into [CSS sprite](https://css-tricks.com/css-sprites/) format that'llll be raddddd :dancer: .  (i.e., pair up the svgs and stitch them together)

**Comment by toolness** [comment]
Hmmmmm, since one version of the icons is essentially just desaturated, another option is [`filter: grayscale(100%)`](https://developer.mozilla.org/en-US/docs/Web/CSS/filter#grayscale%28%29). It (or at least its vendor-prefixed variants) actually appears to have [decent browser support](http://caniuse.com/#feat=css-filters).

**Comment by hannahkane** [comment]
Can we close this one? It's live!

**Comment by sabrinang** [comment]
Yup :)
