### ISSUE TITLE
Have a way to tell what version of site we are running

### ISSUE THREAD

**Issue by mmmavis** [mozilla/teach.webmaker.org#884]
I'm not sure if there's an existing method already but I can't tell what version of the Teach site we are running on PROD (I guess this could apply on STAGING as well?).

Maybe something like https://webmaker.org/healthcheck where we can simply return the version number specified in `package.json` would help?

Updates:
Oh I forgot we have the "dev ribbon" on staging, maybe we can incorporate the `commit` link in `healthcheck` for PROD as well?

**Comment by toolness** [comment]
It's currently available in every generated webpage as a `<meta>` tag. Just use your browser's "view source" (or element inspector) and look for this:

```html
<meta name="git-rev" content="78f92cb254cf376abdfc4b6e8141613086342f59">
```

It would be pretty easy to add a `/heathcheck` page that just displays this. Since the version number in our `package.json` is now meaningful, too, we could also show that.
