### ISSUE TITLE
Mailinglist signup doesn't redirect to our desired section/anchor

### ISSUE THREAD

**Issue by mmmavis** [mozilla/teach.webmaker.org#889]
https://github.com/mozilla/teach.webmaker.org/pull/654 has been merged and pushed `staging`.  For testing purposes, I changed BSD config so that we are redirecting user to `https://teach.mofostaging.net/events/?mailinglist=thanks#mailinglist` for thank you message.  However, BSD appends a bunch of query strings to the URL (e.g., https://teach.mofostaging.net/events/?mailinglist=thanks#mailinglist&action_code=FgxRWxYUOVIKQV0YAFIETFM&td=TVDLTsMwEPwVyycqNandpiQNF04gDhVIcECiyHKSbWPh2JEfFQ_x76zbqsXywTuzs7OeHwqDVJrWdJB75QP4wOcLzvltD1rbM6jMLjcQ6JQ66JSDNojokgwRsYuqOz1FI1EWTpUdg9gnzkStp9Tb6FpArpEeDnrEYnOGsRx7a-DcHyy6ia3S4Gn99o6I2pk4iq11gzh48rJEVetABhBd8p0zvszYMuNzwop6UdTF9aVDjUJ2ncO2kuXlKucVzyt24aMHJ-QOTJq0tt9Ka7mZLXNGrtayVSZY39-QBxNAEwTI4zN5JZzlqxvi9vWizNmE3EP7YTcz3IPh5eQO49raz80s0cmql2NAm7Q_n9JGR9xcKv-FhDLHbxXQlk2xaLMGmirjHIqs6lYyY_8Ojko5GDmk7NbyAxx5ki58kedDSuQKafICsu2JVwEmKBhsFzWcJMcw6e8f) and that breaks the "jump" - page doesn't scroll to the `#mailinglist` form where the thank you message is shown.

**Comment by mmmavis** [comment]
can we fix this by something like

```
if (this.context.router.getCurrentQuery().mailinglist === "thanks") {
    window.location.hash = "mailinglist";
}
```
and remove hash from our redirect URL?

**Comment by toolness** [comment]
Hmm, that might work, though I'm not sure if it'd work on all browsers... Another option is to do something similar to #567 and actually show a modal!

**Comment by hannahkane** [comment]
Just a note that we should prioritize this. MP communications start next week, so we should have this in place by then.

**Comment by toolness** [comment]
Ok. @sabrinang do you have any advice on the UX for this? I'm thinking that a modal would actually be more obvious/noticeable to users than the current design, which just puts the words "Thanks for signing up" in place of the form--we could hack-in ways to make the page scroll to that location on page load, such as [mavis's suggestion above](https://github.com/mozilla/teach.webmaker.org/issues/889#issuecomment-101358262), but doing a modal would be more sure-fire from a technical standpoint since we already do it in other parts of the code. If it's a UX win too, then I recommend we just go with the modal, but otherwise we can try some hacks to ensure that the page scrolls to the right place when BSD brings them back to the site.
