### ISSUE TITLE
Implement approval flow for Clubs

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#911]
detail to come (pending final decisions on https://teach.etherpad.mozilla.org/clubs-signup)

**Comment by toolness** [comment]
I'm noticing that the flow described on the etherpad seems a bit intricate, and someone left the following note there:

> At this stage, don't need to optimize with numbers. Do manually so have a better feel.

Given this, we'll want to find a good balance between writing up new code/UI for the changes versus doing things manually. I suspect there are just a few relatively minor tweaks we can make to the system that will allow the Teach team and RCs to freely iterate on an approval flow; we want to find this sweet spot, so that the staff feels empowered and the engineering team has enough time to focus on the other priorities of the current milestone!

**Comment by toolness** [comment]
Given the fact that clubs will be managed by different individuals with different roles at different times, and that the approval flow will likely involve lots of different phases, I'm wondering if we should add a "staff notes" field to the Club model.

This would be a field that is only visible to staff users of the [admin UI](https://github.com/mozilla/teach.webmaker.org/issues/925#issuecomment-104705395), and they could update it with any information relevant to the current approval flow status of the club that isn't otherwise captured by the system, e.g. "RC alice has set up a 1:1 interview w/ the club lead on june 5". This way more information is stored in the DB for all staff to see, rather than e.g. stuffed in an email thread somewhere that only a few people can see.

**Comment by hannahkane** [comment]
@toolness - does this feel blocked anymore? I think we've removed all of the blockers.

Re: staff notes field—as we talked about at today's stand-up, I'm hoping that, initially, all of the Club management (assigning RCs to clubs, tracking phone calls and emails, scheduling follow-up tasks) will happen in a spreadsheet so that staff and RCs can tweak the process as much as they need without developer involvement. Once the process is stabilized, we can decide whether to add more functionality to the site, to automate or otherwise streamline.

**Comment by toolness** [comment]
Right on, sounds good hannah! This is indeed not blocked anymore IMO, I'll remove the label.

**Comment by toolness** [comment]
We've got a whole lot of the parts in place for this issue, but one important thing that we shouldn't forget to do, and which this issue can perhaps track, is write **documentation** for the new approval flow process, for staff/RCs/admins. We'll probably want to do this collaboratively with the teach team.

**Comment by toolness** [comment]
I'm guessing the best place for such admin docs might be either the GitHub wiki or, actually, the webmaker discourse--particularly if we create a section on that discourse that only teach staff and RCs can access, it could be a good way to both document the administrative UI *and* provide a place for discussing it (I did a similar thing for the hive directory).

**Comment by hannahkane** [comment]
Good call. Do you want to start this, @toolness? Let me know if I can help. 

I'd vote for the GitHub wiki for final documentation. I wonder if we can have the ongoing discussion in github tickets?

**Comment by toolness** [comment]
Ok, I just drafted it here:

https://github.com/mozilla/teach.webmaker.org/wiki/Club-Approval-Flow

Feel free to add or change anything! I will close this ticket now.

**Comment by hannahkane** [comment]
Docs look great. I just added a line to the very end about the automatic state change to Pending if a user edits a Club in the Denied state. Please correct if that's wrong, but I'm pretty sure that's what we talked about.

**Comment by toolness** [comment]
Oh yeah totally, sorry I forgot about that. Thanks for adding it!
