### ISSUE TITLE
Changes to Clubs submission success message

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#920]
- [ ] Change success message copy from "We've added your Club!" to "Thanks for your submission! We'll review it and be in touch shortly."

- [ ] remove "Take me to my club" button action

**Comment by toolness** [comment]
I should also note that we'll need to provide indication about the pending or denied status of a club in the club list/map view. I believe that, along with this issue's original description, are the only changes required for teach.mozlla.org to support the new approval flow. (All the other changes take place in the back-end/teach-api.)

**Comment by toolness** [comment]
Err and #910 is sorta related to this too--I guess ideally it should land before any of this approval flow stuff, since it doesn't require the approval flow, but helps set user expectations for the approval flow once we land it.

**Comment by toolness** [comment]
I was thinking about this, and since (for now) the only way the user can edit their club pre-approval is by actually finding their club on the list or map, I actually think we should *keep* the "Take me to my Club" button in the success/change modals, as it effectively shows the user where they can find their club if they need to edit it before it gets approved.

In a similar vein, I think we should also inform the user that, until we approve their club, their club is only visible to them. What do you think of this success message instead?

![2015-06-01_11-57-16](https://cloud.githubusercontent.com/assets/124687/7917104/dc2113f0-0855-11e5-87d2-768a09c0e49d.jpg)
