### ISSUE TITLE
Club status should be available in a report and/or admin UI

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#925]
@thornet to provide the spreadsheet; Clubs should be added only after they've been approved

The spreadsheet is used to manage the assigning of a Regional Coordinator to every Club

**Comment by toolness** [comment]
Er, wait, this seems like a duplication of data, and can result in all kinds of data synchronization problems.

A more robust alternative might be to have a "region" or "regional coordinator" field for each club, which is only configurable by teach staff in the admin UI. But I'll also admit that I don't fully understand the problem space.

**Comment by thornet** [comment]
@hannahkane thanks for filing! @toolness I'll try to explain the problem:

1. We'd like to add a moderation layer to the "add your club" flow. 
2. When a user applies to add their club, we are notified. 
3. We can then signal whether the club passes moderation (and is added to the map) or is declined (not added). 
4. We'd like for this data to be accessible in some spreadsheet or database so we can see if i) it's been moderated by staff and ii) if it's been assigned a Regional Coordinator.

**Comment by toolness** [comment]
Ah cool, that's no problem at all, Will definitely make sure the admin UI lets you do this.

**Comment by ldecoursy** [comment]
Current admin UI shows active/inactive, so may be an issue of just adding "pending" to the system.

**Comment by toolness** [comment]
As mentioned in #937, there's an existing admin UI that some folks may not know about:

<img src="https://cloud.githubusercontent.com/assets/124687/7755551/eda84148-ffc2-11e4-9b0c-a08a617e9c63.png">

We could potentially have this be the "report" we're talking about in this issue, simply replacing the "is active" column with a "status" column that corresponds to pending, active, and denied.

**Comment by toolness** [comment]
Just an update: in https://github.com/mozilla/teach-api/pull/16, I've updated the admin UI's club list view so it does show the current club approval status:

![2015-05-29_7-42-56](https://cloud.githubusercontent.com/assets/124687/7881933/7b5f85aa-05d6-11e5-8cc8-df118b0437ee.jpg)

Clicking on the "Status" header also allows staff to sort the entries by status.

Note that I haven't actually coalesced the concept of "status" with "is active", which makes things a little bit confusing. This is because doing that would require a non-trivial database migration, which I'm trying to avoid right now... If having both concepts at the same time is really confusing to staff, though, I can coalesce them. (To clarify: if "is active" isn't checked, then the club is essentially treated by the system as though it's deleted, e.g. an approved but inactive club won't show up on the map. The conceptually cleaner solution, which would require a non-trivial DB migration and a bit of code change, would be to remove the "is active" checkbox and instead have another type of club status called "deleted".)

**Comment by toolness** [comment]
Also, we'll eventually have an automated process (run e.g. on a daily or weekly basis) that permanently deletes clubs that have been marked as inactive for over a week, so there won't be too many inactive clubs lying around the system.

**Comment by hannahkane** [comment]
I get the logic, but I do worry that it might be confusing, especially once we open this flow up to volunteer Regional Coordinators. @toolness - want to file a ticket for the coalescing and we can put it into a milestone whenever it begins to feel important?

**Comment by toolness** [comment]
Sure, sounds good! Just filed it as https://github.com/mozilla/teach-api/issues/17... Sorry it is in the teach-api repository, but it really feels like it belongs there... I can move it back here if you want or we can have a "tracking" issue for it here, or something.

**Comment by hannahkane** [comment]
Good to keep it there. Thanks!

**Comment by hannahkane** [comment]
Closing this ticket. Can open a new one if the need emerges.
