### ISSUE TITLE
Decide what icon set we want to use

### ISSUE THREAD

**Issue by mmmavis** [mozilla/teach.webmaker.org#939]
I remember months ago I got an email about switching from Font Awesome to Ionicon for all future Mofo projects.  Is this still valid?  If so we should be consistent about our icon usages on the Teach site, both on the mockups and the build.

Question:
- We are currently using Ionicons for the Teach site, if we are going with Ionicon, are we restricted our icon choices to what @k88hudson 's repo offers? (see https://github.com/mozilla/teach.webmaker.org/blob/develop/package.json#L47)
  - So far the only ionicon occurrence I found on the site is the "download" icon on the [Events page](https://teach.mozilla.org/events/resources/#logo-assets)
- If we are going with Font Awesome, where should we be pulling the icons from? 

/cc @toolness @sabrinang @cassiemc

**Comment by toolness** [comment]
Good question!

Also, while it hasn't been mentioned on this ticket, we are currently using [glyphicons](http://getbootstrap.com/components/#glyphicons) for [some things](https://github.com/mozilla/teach.webmaker.org/search?utf8=%E2%9C%93&q=glyphicon) too, since they come with bootstrap.

**Comment by sabrinang** [comment]
I'd suggest to go with the icons set that is more lightweight and that will load faster on the site for now. There has been mentions between [fontawesome](http://fontawesome.io/) or [ionicons](http://ionicons.com/) but that discussion is still up in the air. I'd say we pick and stay with one set and since we already have ionicons used on the teach website let's stick with that and avoid using another set like [glyphicons](http://getbootstrap.com/components/#glyphicons) and replace any current icons used with ionicons. Moving forward I will also use ionicons in the design mockups too.

**Comment by cassiemc** [comment]
My preference is to stick with fontawesome until we have clearly analyzed the pros/cons of switching. @gvn had some good input and arguments for fontawesome when we first raised the discussion. Not sure if @vazquez has further input.

**Comment by mmmavis** [comment]
Hey @sabrinang I'm assigning this ticket to you since you are the decision maker.

I see FontAwesome icons are used in a few latest mockups(e.g., [here](https://github.com/mozilla/teach.webmaker.org/issues/908)).  Just wanna confirm with you that we can drop Ionicons for FontAwesome now.

We use quite a bit of glyphicons on the Teach site and since the set is loaded as part of Bootstrap package anyway, I think we can just keep Glyphicons.

**Comment by sabrinang** [comment]
Let's continue with FontAwesome until further notice and we can streamline our icons by using this 1 icon set when possible.
