### ISSUE TITLE
Optimize hero unit images

### ISSUE THREAD

**Issue by mmmavis** [mozilla/teach.webmaker.org#946]
As mentioned in https://github.com/mozilla/teach.webmaker.org/pull/943#issuecomment-105556993

**Comment by toolness** [comment]
I was just watching a CSSConf presentation on [CSS Performance Tooling](https://www.youtube.com/watch?v=FEs2jgZBaQA&list=PL37ZVnwpeshHAnqFlTxhd0MIXWjLBbM3R) and the speaker mentioned a tool called [gulp-imagemin](https://github.com/sindresorhus/gulp-imagemin), which would allow us to do the image optimization during the build/deploy phase rather than during development. I like this approach a lot because it means we can optimize for quality during development and then easily scale to whatever target quality we want for production, without having to do any manual fiddling.

The speaker also mentioned [gulp-svgmin](https://www.npmjs.com/package/gulp-svgmin) which could be useful for optimizing our SVGs.

**Comment by toolness** [comment]
Hmm, so I attempted to play around with gulp-imagemin a bit today and ran into a few things:

* Blanketly applying the plugin to all our images as part of our `copy-images` task seems to make the node process exit without providing any traceback. This is very annoying.
* Selectively applying the plugin to an individual PNG file works. I tried doing it to the portrait of Mikko and it shaves off a few KB, but when I tried doing it on the homepage hero unit (both retina and standard), the size stayed the same, even when I upped the optimization to the maximum level (7). I wonder if this has something to do with us using PNGs instead of JPEGs? Not entirely sure...

**Comment by mmmavis** [comment]
thanks for taking this over @toolness  :smiley_cat:

**Comment by toolness** [comment]
No probs mavis!

So it seems like the imagemin thing is specifically intended for *lossless* minification, whereas I think that we'll actually need to loss-fully (is that the right word?) compress some of our images to really save on space. I'll look at a module called [`lwip`](https://github.com/EyalAr/lwip) which allows us to do basic image manipulation and could help us automate loss-fully converting some of our assets.

**Comment by toolness** [comment]
From my [above comment](https://github.com/mozilla/teach.webmaker.org/issues/946#issuecomment-110430743):

> Hmm, so I attempted to play around with gulp-imagemin a bit today and ran into a few things:
>
> * Blanketly applying the plugin to all our images as part of our `copy-images` task, via `.pipe()`, seems to make the node process exit without providing any traceback. This is very annoying.

I was actually having a similar problem when using an entirely different library to process our images in #1026, and found that upgrading node from v0.12.0 to v0.12.4 fixed things on my Windows machine. I haven't tried `gulp-imagemin` again, but I suspect it was crashing due to the same underlying bug.

**Comment by toolness** [comment]
Hmm, so `gulp-imagemin` still makes gulp silently exit, though it does so with an exit code of 0 (my [aforementioned problem](https://github.com/mozilla/teach.webmaker.org/issues/946#issuecomment-112082192) with the other library caused a nonzero exit code).

I tried using [`imagemin-optipng`](https://github.com/imagemin/imagemin-optipng) instead, to only optimize PNG files, and it does work, but the optimization takes a relatively long time--about 1.2 minutes with an optimization level of 3. So either I can do some further investigating to figure out if there are particular files that are causing it to take so long, or we can reduce the optimization level, or we can only apply the plugin for production.
