### ISSUE TITLE
mobile view just shows the back of a head

### ISSUE THREAD

**Issue by davidascher** [mozilla/teach.webmaker.org#958]
which isn't that inviting:

![2015-05-29 01 46 19](https://cloud.githubusercontent.com/assets/51278/7874833/ec744d7e-0569-11e5-9ada-dd49d67274bb.png)

**Comment by hannahkane** [comment]
This is actually a more generic problem, on all pages. Closing #538 which this dupes.

**Comment by hannahkane** [comment]
Actually, I was wrong. This is specific to the homepage because it's related to the three buttons. Let's look into a CSS-based solution where we change the position of the buttons on mobile.

**Comment by mmmavis** [comment]
@toolness would changing the `background-position` of `.hero-unit` from `right top` to `center top` help?  That way we can at least guarantee the center section of the background image is shown on smaller devices.

**Comment by toolness** [comment]
Ah yeah that would be perfect!

Perhaps it might be useful to tweak `background-position` on a per-hero-unit basis, depending on the visual structure of the hero image? For instance, some hero units might have the main action on the right side of the photo, rather than the center.

Hmm, looking at the hero images we've got, though, it *does* look like the main action is in the center for all of them. I guess an easy way to find out is just to issue a simple PR that makes the change universally, merge it, and then point hannah and sabrina to staging so they can see how it looks?
