### ISSUE TITLE
Blog posts tagged with #teachtheweb not appearing on teach.mozilla.org

### ISSUE THREAD

**Issue by ldecoursy** [mozilla/teach.webmaker.org#963]
On the homepage on teach.mozilla.org, it looks like the most recently featured post is from May 12th, however there is a more recent post with the #teachtheweb tag that is not appearing.

![screen shot 2015-06-01 at 9 00 16 am](https://cloud.githubusercontent.com/assets/4885898/7913290/b80441e0-083c-11e5-90ae-3ccfebaf769d.png)

When I click the "See all blog posts link" I see the Maker Party blog post from May 18th, but it's not appearing on the teach homepage. 

cc @KevZawacki

**Comment by toolness** [comment]
Sorry about that, this is just because #950 hasn't landed yet--the blog posts that are showing right now on teach.mozilla.org are actually hard-coded into the site, but once it lands and we push it to prod (hopefully today or tomorrow) the latest blog posts will definitely be showing up!

Sorry we didn't communicate this to you earlier, we just [really wanted](https://github.com/mozilla/teach.webmaker.org/pull/952#issuecomment-106608683) to push the new homepage to prod last week, even if its blog posts were a bit out of date :)

**Comment by toolness** [comment]
I suppose we don't have a formal "bug" filed that #950 fixes, so I guess this is it. We can just close this issue once that PR is merged.

**Comment by toolness** [comment]
Ok, #950 just landed and is part of the [v0.0.8](https://github.com/mozilla/teach.webmaker.org/releases/tag/v0.0.8) release we just forged. It should be live on production in a few minutes!

**Comment by toolness** [comment]
Gah, my bad--we landed #950, but didn't hook up the homepage to actually *use* the new functionality to dynamically fetch the blog posts. This is a one-line fix, I'll re-issue a new release to make sure this goes out before EOD today.
