### ISSUE TITLE
Explore Discourse integration

### ISSUE THREAD

**Issue by hannahkane** [mozilla/teach.webmaker.org#997]
Need to discuss what the actual deliverable might be, but want to ensure we do some work to advance the Discourse integration project.

**Comment by hannahkane** [comment]
Lo-fi wireframes needed for low-bar integration

**Comment by toolness** [comment]
I think I'll also play around with the discourse API to see what's possible and what's not.

**Comment by toolness** [comment]
It looks like Discourse has a handy [API](https://meta.discourse.org/t/discourse-api-documentation/22706) that gives us pretty easy access to the latest and most popular topics in a variety of formats, including e.g. [JSON](http://discourse.webmaker.org/latest.json) and [RSS](http://discourse.webmaker.org/latest.rss). So that's cool.

It should be pretty straightforward for us to integrate however we like in a read-only fashion.

**Comment by hannahkane** [comment]
Added https://github.com/mozilla/learning-networks/issues/196 for discussion about what we'd want to include on a page of Discourse content

**Comment by hannahkane** [comment]
Closing this. It's been explored. :)
